### ISSUE TITLE
SDK does not compile with Xcode 14 / Swift 5.7

### ISSUE THREAD

**Issue by JanGorman** [RevenueCat/purchases-ios#1663] opened 2022-06-07 07:06 UTC
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Development/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
The RevenueCat SDK does not compile with the latest version of Xcode. There is a compiler error:

`Stored properties cannot be marked potentially unavailable with '@available'`

Coming from https://github.com/RevenueCat/purchases-ios/blob/main/Sources/Support/BeginRefundRequestHelper.swift#L30 and a few other files that add an `@available` to properties.

1. Environment
   1. Platform: iOS
   2. SDK version: 4.5.1
   3. StoreKit 2 enabled (Y/N):
   4. OS version: 16
   5. Xcode version: 14.0 beta (14A5228q)
   6. How widespread is the issue. Percentage of devices affected.
2. -na-
3. Build with Xcode 14
4. -na-

**Comment by het-prajapati** [comment] 2022-06-07 10:24
Having a similar issue. Hoping to get a fix soon
<img width="1512" alt="Screen Shot 2022-06-07 at 3 53 04 PM" src="https://user-images.githubusercontent.com/49564587/172357659-a74755c0-6c57-4679-b1a3-787d18280ec0.png">
!

**Comment by dqhieu** [comment] 2022-06-07 14:27
Getting the same issue

**Comment by NachoSoto** [comment] 2022-06-07 14:47
Duplicate of #1660, which is already fixed by #1661 in `main`.

**Closed** 2022-06-07 14:47 UTC
Labels: bug
