### ISSUE TITLE
Attempts to subscribe to an existing subscription are reported as `.storeProblemError` with a message of "An unknown error occurred".

### ISSUE THREAD

**Issue by xsleonard** [RevenueCat/purchases-ios#392] opened 2020-11-14 07:54 UTC
Attempts to subscribe to an existing subscription are reported as `.storeProblemError` with a message of "An unknown error occurred".

> PaymentQueue removedTransaction: appname (null) ((null) Error Domain=SKErrorDomain Code=0 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred, NSUnderlyingError=0x282e3ee50 {Error Domain=ASDServerErrorDomain Code=3532 "You’re currently subscribed to this." UserInfo={NSLocalizedDescription=You’re currently subscribed to this.}}}) {
    NSLocalizedDescription = "An unknown error occurred";
    NSUnderlyingError = "Error Domain=ASDServerErrorDomain Code=3532 \"You\U2019re currently subscribed to this.\" UserInfo={NSLocalizedDescription=You\U2019re currently subscribed to this.}";

To reproduce:

- Purchase some subscription with a sandbox user
- Try to purchase that same subscription
- An alert box will be presented with the title "You're current subscribed to this" with alert actions of "Manage | OK"
- Pressing OK eventually results in the console log output above

This is a problem because this handling of this error is different than other kinds of store errors, as described in https://docs.revenuecat.com/docs/errors#--store_problem, and this purchase request will not or should not be retried.

- Purchases v3.7.6
- iOS 14.0
- Sandbox

**Comment by rkotzy** [comment] 2020-11-16 17:16
Hmm Apple used to send back a SKErrorDomain Code 2 in this scenario, which indicated a cancellation. I'm wondering if this case is specific to sandbox 🤔

The SKErrorDomain Code 0 is an Unknown Error from Apple, which RevenueCat maps to store problem: https://developer.apple.com/documentation/storekit/skerror/code/unknown

It doesn't seem like Apple has any documentation on the `ASDServerErrorDomain` codes, so it's unclear if they're safe to trust. 

Related: https://developer.apple.com/forums/thread/664977

**Comment by thattridentdude** [comment] 2021-03-22 23:50
Not sure if I'm too late to the party, but if there's still the question of this being specific to the sandbox or not, I can provide some insight.  

I can confirm this is not sandbox specific and also occurs in the wild. I had a user that was experiencing issues send me some logs and it's almost verbatim what @xsleonard got in the sandbox environment, the localized description in the production environment seems slightly tweaked.  

Here is what I have captured in logs, please ignore the emojis, I use those to determine log level. 
I'll cut up per event::

> 15:25:44.933 ☢️ Purchase Failed Readable: STORE_PROBLEM  || 00:01:10.294
15:25:44.950 ☢️ Purchase Failed Debug: There was a problem with the App Store.  || 00:01:10.311
15:25:44.957 ☢️ Purchase Failed Underlying Error: Error Domain=SKErrorDomain Code=0 "(null)"  || 00:01:10.317

> 15:27:40.281 ☢️ Purchase Failed Readable: PURCHASE_CANCELLED  || 00:03:05.641
15:27:40.288 ☢️ Purchase Failed Debug: Purchase was cancelled.  || 00:03:05.648
15:27:40.292 ☢️ Purchase Failed Underlying Error: Error Domain=SKErrorDomain Code=2 "(null)" UserInfo={NSUnderlyingError=0x282e80f90 {Error Domain=ASDErrorDomain Code=907 "Unhandled exception" UserInfo={NSUnderlyingError=0x282f52970 {Error Domain=AMSErrorDomain Code=6 "Payment Sheet Failed" UserInfo={NSLocalizedDescription=Payment Sheet Failed, NSLocalizedFailureReason=Payment sheet cancelled}}, NSLocalizedFailureReason=An unknown error occurred, NSLocalizedDescription=Unhandled exception}}}  || 00:03:05.653

> 15:27:57.057 ☢️ Purchase Failed Readable: PURCHASE_CANCELLED  || 00:03:22.418
15:27:57.069 ☢️ Purchase Failed Debug: Purchase was cancelled.  || 00:03:22.430
15:27:57.078 ☢️ Purchase Failed Underlying Error: Error Domain=SKErrorDomain Code=2 "(null)" UserInfo={NSUnderlyingError=0x282ee9740 {Error Domain=ASDErrorDomain Code=907 "Unhandled exception" UserInfo={NSUnderlyingError=0x282eeb9f0 {Error Domain=AMSErrorDomain Code=6 "Payment Sheet Failed" UserInfo={NSLocalizedDescription=Payment Sheet Failed, NSLocalizedFailureReason=Payment sheet cancelled}}, NSLocalizedFailureReason=An unknown error occurred, NSLocalizedDescription=Unhandled exception}}}  || 00:03:22.439

> 15:28:07.834 ☢️ Purchase Failed Readable: STORE_PROBLEM  || 00:03:33.195
15:28:07.857 ☢️ Purchase Failed Debug: There was a problem with the App Store.  || 00:03:33.217
15:28:07.868 ☢️ Purchase Failed Underlying Error: Error Domain=SKErrorDomain Code=0 "(null)"  || 00:03:33.229

> 15:29:24.964 ☢️ Purchase Failed Readable: STORE_PROBLEM  || 00:00:18.652
15:29:24.970 ☢️ Purchase Failed Debug: There was a problem with the App Store.  || 00:00:18.657
15:29:24.972 ☢️ Purchase Failed Underlying Error: Error Domain=SKErrorDomain Code=0 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred, NSUnderlyingError=0x283e96cd0 {Error Domain=ASDServerErrorDomain Code=3532 "You are currently subscribed" UserInfo={NSLocalizedDescription=You are currently subscribed}}}  || 00:00:18.660

> 15:31:48.168 ☢️ Purchase Failed Readable: STORE_PROBLEM  || 00:02:41.856
15:31:48.179 ☢️ Purchase Failed Debug: There was a problem with the App Store.  || 00:02:41.867
15:31:48.182 ☢️ Purchase Failed Underlying Error: Error Domain=SKErrorDomain Code=0 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred, NSUnderlyingError=0x283ed6c10 {Error Domain=ASDServerErrorDomain Code=3532 "You are currently subscribed" UserInfo={NSLocalizedDescription=You are currently subscribed}}}  || 00:02:41.870

At the risk of being redundant, the "Readable" line prints out ReadableErrorCodeKey, the "Debug" prints out localizedDescription and "Underlying Error" prints out NSUnderlyingErrorKey.  


As you can see the events start with what seems to be a legitimate store problem (personally I suspect a connectivity issue), followed by two payment sheet cancellations then another classic store problem error and then two store problem errors with the "You are currently subscribed" string. 

Here's the kicker though; during all this, somewhere, somehow a transaction was successful and not only ended up in the transaction history of the user's Apple ID, but also in RC's backend ($RCAnonymousID is available if you think it helps), yet entitlement on the app's side remains nil even though I check the entitlements regardless of error. On the side of the app there is no trace of a successful transaction, aside from the fact that the last two store problem errors indicate that the user is already subscribed. 

Obviously this is undesirable behavior in a production environment. 

It seems this user hasn't tried to restore purchases and instead just repeatedly tried to purchase the same subscription, I've asked them to reinstall for good measure and then restore the purchase, but haven't heard back from them and I don't see a new alias created for this ID in RC's dashboard so I think they haven't tried out my suggestion yet. 

I don't have much other information, but feel free to let me know if I can be of further assistance.

**Comment by xsleonard** [comment] 2021-03-23 03:38
Another report of this error in the wild (`SKErrorDomain Code=0, ASDServerErrorDomain Code=3532`), https://developer.apple.com/forums/thread/664977

**Comment by aboedo** [comment] 2021-03-23 15:26
@thattridentdude thanks for the detailed report. 
It does look like something went wrong the first time, where the transaction actually did go through but iOS didn't see it as a success, probably because it didn't get a response from App Store, which might be due to a connectivity issue. 
The backend did however see the update, either because the SDK posted the receipt or because of an App Store server-to-server notification. 
So the good news is that in a case like this, the system should auto-recover: 
- if the app remains open, the SDK caches user info for a max of 5 mins (a bit longer if the app is used solely in the background).
- force-closing and re-opening the app would trigger a purchaserInfo update
- A fresh install + restore transactions should also work in terms of fixing. 

In all of these cases, the best way for the app to be prepared is to implement the [RCPurchasesDelegate](https://github.com/RevenueCat/purchases-ios/blob/develop/Purchases/Public/RCPurchases.h#L557), so that you can react to new purchaserInfo accordingly. 

I'm not sure what the best way for the SDK to handle this would be. The problem is that StoreKit itself is returning an "unknown" error, so the SDK could in theory force refresh purchaserInfo whenever there's an "unknown" error, but could also produce a large number of unnecessary receipt refreshes.

**Comment by aboedo** [comment] 2021-03-23 15:31
I'm going to think about this further and see what we can do to improve behavior. For now, though, the ways for the system to auto-recover are listed in my previous comment. I hope that helps!

**Comment by thattridentdude** [comment] 2021-03-23 23:36
@aboedo Thanks for looking into this. 

Yeah I think this ended up on the RC backend via a server-to-server notification. 
I have implemented the delegate, but that didn't help in this case. I was going to do an overhaul of some of the logic anyways and use the Magic Weather example app to see where I can improve stuff, so I'll double check if the delegate was properly implemented but it's a pretty simple extension in AppDelegate comes verbatim from the documentation [here](https://docs.revenuecat.com/docs/purchaserinfo#listening-for-purchaser-info-updates) and simply does an entitlement check and updates variables used by business logic, so I'm not sure if there is anything to improve to begin with. 

Like I said, I've instructed user to reinstall and restore, but I haven't heard anything back about that not working (which is usually good news).  

As for the best way for the SDK on how to handle this, that's a tough one to be honest. It seems Apple might've changed the SKErrorDomain Code for this, which would require remapping some stuff, but on the other hand it's not entirely clear if this is even intended behavior and remapping would mean that you'd have to rely on the ASDServerErrorDomain Code and/or the localizedDescription string. 

You've mentioned the solution of the SDK doing a force refresh or to rely on auto-recovery through the delegate, but both seem rather bandaid solutions aimed at symptoms. 

Perhaps RC or us devs can get some clarification regarding this from (someone at) Apple? Either though one of the engineers that frequents the dev forum (e.g. esk1mo), general dev support or via DTS/TSI or, if even available, through a liaison that RC might have access to?

**Comment by aboedo** [comment] 2021-03-26 18:50
@thattridentdude we're going to do a mix, where we actually try to handle cases with `ASDServerErrorDomain` and contacting Apple to try to figure out when this would happen and how best to handle it. Thanks for your feedback and patience!

**Comment by tanmays** [comment] 2021-08-07 12:21
I just encountered this during testing in sandbox on iOS 15. In my case the error stays even after re-installing the app. Here's what I did. 

1. In Settings (iOS 15) > App Store > set Sandbox account initially to a non-sandbox account (i..e to an actual Apple ID not added to sandbox users on App Store Connect)
2. Attempt to purchase in the sandbox, every step will succeed until the last where it will error out saying this ID is not authorised for sandbox purchases.
3. Now go into Settings and add the authorized sandbox account. 
4. Any future attempts to purchase result in an error with the following error log: 

```
Error Domain=SKErrorDomain Code=0 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred, NSUnderlyingError=0x28247dbf0 {Error Domain=ASDServerErrorDomain Code=3532 "You’re currently subscribed to this." UserInfo={NSLocalizedDescription=You’re currently subscribed to this.}}}) {
                     NSLocalizedDescription = "An unknown error occurred";
                     NSUnderlyingError = "Error Domain=ASDServerErrorDomain Code=3532 \"You\U2019re currently subscribed to this.\" UserInfo={NSLocalizedDescription=You\U2019re currently subscribed to this.}";
```

**Comment by aboedo** [comment] 2021-08-09 17:55
@tanmays thanks for reporting. We're going to take care of this one, but I unfortunately don't have an ETA for it yet.

**Comment by NachoSoto** [comment] 2021-11-18 00:52
Proposed solution: #965.

**Closed** 2021-11-18 16:23 UTC
Labels: triaged
