### ISSUE TITLE
[SANDBOX] StoreKit config not working when using Xcode 14/iOS 16 beta 3

### ISSUE THREAD

**Issue by ZeeWanderer** [RevenueCat/purchases-ios#1765] opened 2022-07-18 13:36 UTC
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Development/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
StoreKit configuration file stopped working on XCode 14 beta 3 + iOS 16 beta 3, the same configuration works on XCode 13.4.1 + IOS 15.5. I tried resaving public testing certificate with beta xcode but it produces the same file. I also tried recreating Config file with Xcode 14. Logs attached, thou logs for ios15.5+Xcode13.4.1 are from a simulator as rn i don't have a real device with 15.X to produce the log.

1. Environment
   1. Platform: iOS
   2. SDK version: 4.9.0
   3. StoreKit 2 (_enabled with `useStoreKit2IfEnabled`_) (Y/N): N
   4. OS version: 16 beta 3
   5. Xcode version: 14 beta 3
   6. How widespread is the issue. Percentage of devices affected.
2. [RC_ios15.5+Xcode13.4.1.log](https://github.com/RevenueCat/purchases-ios/files/9132176/RC_ios15.5%2BXcode13.4.1.log)  [RC_ios16.b3+Xcode14.b3.log](https://github.com/RevenueCat/purchases-ios/files/9132335/RC_ios16.b3%2BXcode14.b3.log)
3. 
4. 

**Additional context**

**EDIT:**
If StoreKit 2 is enabled the config works fine
log: [RC_ios16.b3+Xcode14.b3+SK2.log](https://github.com/RevenueCat/purchases-ios/files/9132398/RC_ios16.b3%2BXcode14.b3%2BSK2.log)

**Comment by beylmk** [comment] 2022-07-18 18:39
Hey @ZeeWanderer, thanks for the detailed issue. It's definitely possible this was broken in the latest xcode beta release. I'll try it out myself, but need to download beta 3 first 😅 will report back here once done!

**Comment by beylmk** [comment] 2022-07-19 15:18
Hey @ZeeWanderer, quick update -- we confirmed that StoreKit config files work for our sample app in Xcode 14 beta 3 +ios 16 beta 3. We did see the method `SkTestSession.expireSubscription` crash sometimes, but don't think that's related to your issue... 

Looking at the logs, it appears that the successful ios16/xcode14 run didn't make an SKProductsRequest because our SDK already cached products on the device. The SKProductsRequest is the one that fails later on.

Can you please confirm whether the  iOS 16/Xcode 14/useStoreKit2IfEnabled true combination still works after uninstalling and reinstalling the app?

**Comment by ZeeWanderer** [comment] 2022-07-25 09:59
Yes, iOS 16/Xcode 14/useStoreKit2IfEnabled true combination works with clean app install.
log: [RC_ios16.b3+Xcode14.b3+SK2+clean_install.log](https://github.com/RevenueCat/purchases-ios/files/9180073/RC_ios16.b3%2BXcode14.b3%2BSK2%2Bclean_install.log)

**Comment by ZeeWanderer** [comment] 2022-08-01 09:19
On Xcode 14 beta 4 and iOS 16 beta 4 still the same thing. Without SK2 enabled using the StoreKit config results in fetching error.
Logs:
[RC_ios16.b4+Xcode14.b4.log](https://github.com/RevenueCat/purchases-ios/files/9232486/RC_ios16.b4%2BXcode14.b4.log)
[RC_ios16.b4+Xcode14.b4+SK2+clean_install.log](https://github.com/RevenueCat/purchases-ios/files/9232567/RC_ios16.b4%2BXcode14.b4%2BSK2%2Bclean_install.log)

**Comment by taquitos** [comment] 2022-08-02 17:07
Heya, we've got a broader testing initiative for iOS 16 compatibility that we're going to be doing when the GM is available. Unfortunately, we haven't been able to reproduce this yet but we're going to keep trying. For now, I'd suggest sticking with the SDK default config. It uses a mix of SK1 and SK2- SK2 where the API is more accurate/less error prone.

**Comment by NachoSoto** [comment] 2022-08-02 18:06
Thanks a lot for attaching those logs. That made me realize that we were not exposing the underlying error returned by `StoreKit`, so I fixed that: #1792

**Comment by NachoSoto** [comment] 2022-08-02 18:20
That PR was just merged. We're not sure when the next release will be out, but if you're able to test with `main`, we'd love to see exactly why your product request is failing 🙏🏻

**Comment by ZeeWanderer** [comment] 2022-08-03 13:06
Here is the log for master ([9b5b3f2](https://github.com/RevenueCat/purchases-ios/commit/9b5b3f26e642624cdc0f53a92f92d282d4fcdded)), no SK2 and clean install.
[RC_ios-main+XCode14.b4+ios16.b4+no-SK2+clean_install.log](https://github.com/RevenueCat/purchases-ios/files/9251532/RC_ios-main%2BXCode14.b4%2Bios16.b4%2Bno-SK2%2Bclean_install.log)

**Comment by NachoSoto** [comment] 2022-09-16 18:21
@ZeeWanderer are you still seeing this issue on Xcode 14 RC?

**Comment by ZeeWanderer** [comment] 2022-09-16 19:36
@NachoSoto Yes, it still requires SK2 to work with store kit config. 
XCode 14, iOS 16, SDK 4.12.0.

**Comment by NachoSoto** [comment] 2022-12-13 16:29
I recommend filing a Feedback with Apple if you're still seeing this issue, as it's likely an Xcode bug.

**Closed by NachoSoto** 2022-12-13 16:29 UTC
Labels: bug, triaged
