### ISSUE TITLE
Swift paywall with square edges

### ISSUE THREAD

**Issue by alamodey** [RevenueCat/purchases-ios#445] opened 2021-01-12 10:47 UTC
Hi, using the swift paywall in the examples. How come on the iPad the edges are square even though the default initialisation is with a round paywall. There are no issues on the iPhone though. 

![IMG_B2AB8C2E4153-1](https://user-images.githubusercontent.com/55496019/104304540-9a89c780-551f-11eb-8761-4398f817714d.jpeg)

![IMG_B3FC55CFC420-1](https://user-images.githubusercontent.com/55496019/104304595-ab3a3d80-551f-11eb-8def-1b8645ec45c8.jpeg)

**Comment by aboedo** [comment] 2021-01-14 18:27
Hi! Thanks for reporting. This is a bug in the example paywall. The problem is actually that the sizing constraint doesn't work correctly for iPad (or Mac), so the collection view cell is actually too large to fit, so it gets clipped off at the top and bottom. 

The paywall in the sample app isn't meant to be a perfect drop-in replacement to use in your app, it's meant to demonstrate how to use the SDK, as well as provide a starting point if needed. 

If you want to fix this in your app, you can head over to `SwiftPaywall.swift`, and within `SwiftPaywall`, look for `widthPerPackage`, and set a maximum width for it. 
That will in turn set a maximum height, since they're set up with a fixed aspect ratio, and will allow for the content to fit. 

Here's an example setting a max of 300 pixels: 
```swift
// This determines the cell size
private var widthPerPackage : CGFloat {
    let paddingSpace = sectionInsets.left * (maxItemsPerRow + 1)
    let availableWidth = view.frame.width - paddingSpace
    let maxWidth:CGFloat = 300.0
    return min(availableWidth / maxItemsPerRow, maxWidth)
}
```

Note that the reason this works for iPhone is that the cards will never actually get big enough for it to be a problem, so setting a max width that's larger than the max value it gets on iPhone should safely cover it. 

There might still be other things that look less-than-ideal with the UI on iPad, though. 

I'm closing this for now, since like I mentioned before, the paywall is meant more as a starting point / demo than anything else, but I do hope my suggestions help.

**Closed by aboedo** 2021-01-14 18:27 UTC
Labels: bug

**Comment by alamodey** [comment] 2021-01-14 20:46
Thanks, setting the maxWidth at 150 fixed the issue. 

Although you don't regularly update your sample SwiftPaywall, I think it is worthwhile to occasionally refresh it. There's a lot of solo developers that want the most frictionless experience to getting their IAP up and running. I think I gave some previous feedback on how the default labels were getting rejected by the App Store - I'm sure I'm not the only one that is using this paywall and getting these issues. But overall it's good template that covers 99% of what Apple want to see.

**Comment by aboedo** [comment] 2021-01-15 14:25
I agree. I made a PR with the fix yesterday. And you're correct, the paywall is used by many developers, so although it's not meant to be a perfect drop-in paywall, it's worth keeping it in good shape. Thanks again for reporting and for the feedback!
