### ISSUE TITLE
Unable to compile in Xcode 11.4 Beta 2

### ISSUE THREAD

**Issue by WillBishop** [RevenueCat/purchases-ios#185] opened 2020-02-20 06:51 UTC
Hey!

I use purchases in an iPadOS app and ever since Xcode 11.4 Beta 1 (and persisting through to Beta 2), I haven't been able to compile my app.

Upon compiling, I get 7 errors
<img width="375" alt="image" src="https://user-images.githubusercontent.com/17292672/74908185-1f01c200-5405-11ea-9e90-775650e65ebd.png">

**Comment by vegaro** [comment] 2020-02-20 06:53
How are you adding our SDK to your app?

**Comment by WillBishop** [comment] 2020-02-20 06:56
Through SPM.

After updating to 3.0.4, the above errors go away, but are replaced with 11 more.

![image](https://user-images.githubusercontent.com/17292672/74908574-165dbb80-5406-11ea-9fc1-e4b335f788a7.png)

**Comment by andreagelati** [comment] 2020-02-20 11:14
The same here, same kind of errors.

**Comment by aboedo** [comment] 2020-02-20 17:00
I'm able to reproduce, although unfortunately I don't have a fix yet. 
This only happens in Swift Package Manager, in my testing Cocoapods and Carthage work on Xcode 11.4 beta 2, so one solution is to use them instead until this is fixed if you're using Xcode 11.4

**Comment by lisindima** [comment] 2020-03-05 01:50
Hi everyone, this bug is fixed for me with Xcode 11.4 beta 3, but such a warning appears during assembly.
<img width="1222" alt="Снимок экрана 2020-03-05 в 08 49 03" src="https://user-images.githubusercontent.com/43087859/75939981-65075d00-5ebe-11ea-8828-258adbd02b47.png">

**Comment by aboedo** [comment] 2020-03-05 15:44
Thanks for the heads up @lisindima. I believe Xcode 11.4's SPM seems to have changed the way that it determines which source files to compile, so the warning is just saying "this is a plist, I'm not sure how to compile this". 
It should still work fine, however, I'll add an exception for that file so that the warning goes away. There's a chance that it goes away by the next Xcode release, though. 
The previous error we had (duplicate rule compilation) meant "I was asked to compile this file more than once), which is why I believe the underlying issue is that Xcode changed the way it determines which source files to compile.

**Comment by aboedo** [comment] 2020-03-05 19:51
indeed, adding 
```
exclude: ["Purchases/Info.plist"],
```
in the target definition in Package.swift does do get rid of the warning. This being a minor release, I think they'll probably fix the issue on Xcode side before the final 11.4, since the overall spec shouldn't have changed. I'll add the change regardless, as a part of #183

**Comment by aboedo** [comment] 2020-03-25 18:21
update here: the relevant changes have been merged into master. They'll also be a part of the next release, 3.2.0, which will be out soon.

**Comment by aboedo** [comment] 2020-03-26 13:59
update again: the changes have been released 🎉 . Closing this issue

**Closed by aboedo** 2020-03-26 13:59 UTC
