### ISSUE TITLE
RCAnonymousID doesn't change after identify

### ISSUE THREAD

**Issue by ichikmarev** [RevenueCat/purchases-ios#266] opened 2020-06-23 13:35 UTC
Our app have it’s own user uid’s and usually client obtaining it from backend after installation and login. We follow all the guides on RC identification written here:  [https://docs.revenuecat.com/docs/user-ids#section-tips-for-setting-app-user-ids](https://docs.revenuecat.com/docs/user-ids#section-tips-for-setting-app-user-ids)  but it’s still didn’t works how we expect. So here the problem and steps to reproduce:

1 First we configure Purchases with nil on *appUserId*, so SDK creates *RCAnonymousID*
2 After login and obtaining our own id, we call identify method, with our id as parameter
3 In method closure(*RCReceivePurchaserInfoBlock*) info contains wrong *originalAppUserId*
4 And purchaserInfo method are also contains wrong *originalAppUserId*

We expect here to see our own id. We have an Android app, built the same way, and the issue doesn’t reproduce on it.

Also we made some research, and if we call *Purchases.shared.appUserID* in same closure, it will be correct one
We thought that maybe there’s a problem with UserDefaults which RC uses as storage.
If we call *UserDefaults(suiteName: «»)?.dictionaryRepresentation()* we can’t find any correct id

What suggestions and tips do you have for our problem? Version 3.4.0

**Comment by leocassioo** [comment] 2020-07-01 19:03
I am experiencing the same problem with my iOS application. Even giving a reset I could not solve the problem, whenever I enter a new user and do the account, it replaces the data from the previous one.

```swift
Purchases.shared.reset({ (info, error) in
}
```

**Comment by ichikmarev** [comment] 2020-07-02 08:09
@aboedo @vegaro sorry guys, but RC support didn't tell us anything, and issue still here and more related to SDK

**Comment by aboedo** [comment] 2020-07-02 13:43
hi, sorry for the delayed response. I’m going to try to dig into it and see what’s going on and I’ll get back to you.

**Comment by aboedo** [comment] 2020-07-02 20:14
I've been trying this locally and it doesn't seem to reproduce for me... And the code seems okay, which makes me think that the culprit may be user defaults not flushing. Perhaps we need to manually call `synchronize`, even though it's not _supposed_ to be necessary. 
Which version of iOS have you seen this with? Which device?

**Comment by sou1t** [comment] 2020-07-03 05:09
We tested on iOS 13.5.1, the problem was on all iphone models.

**Comment by leocassioo** [comment] 2020-07-03 11:47
@aboedo 
Here it is occurring in 13.5.1

Right after logging in, I do `Purchases.shared.identify`, but when making the purchase, the user is considered the same as the previous one logged in. And updating the `App User ID` on the dashboard, making the 2 users into just 1.

This happens by providing `Purchases.shared.reset` or not when the old user logoff.

**Comment by sou1t** [comment] 2020-07-06 10:00
@aboedo, our iOS team would like to call your engineers at a convenient time. We want to solve this issue as soon as possible. Is such solution possible? By the way, we already signed up for your webinar with a demo on July 8.

**Comment by jeiting** [comment] 2020-07-06 13:17
> 3 In method closure(RCReceivePurchaserInfoBlock) info contains wrong originalAppUserId

Can you clarify what you mean by "wrong"? i.e. are you expecting your server generated ID to be the originalAppUserId? That won'y be the case because you initialized the SDK with an anonymous id, which because the "original" app user id.

**Comment by sou1t** [comment] 2020-07-06 13:52
@jeiting I expect that an anonymous ID will never make a purchase. I assign our system's ID before the user completes the purchase and expect that purchase will be listed on the ID that I specified in the method "identify".

**Comment by jeiting** [comment] 2020-07-06 14:04
>  expect that purchase will be listed on the ID

Can you clarify what you mean by this? What does "will be listed on the ID" mean? Likely the ID you passed to identify is aliased with the anonymous id, which is the current behavior of our SDK. You should be able to access the purchase using your passed in ID, or the ID we generated. The existence of the anonymous ID shouldn't matter.

**Comment by sou1t** [comment] 2020-07-06 14:13
It seems like there is a bug in identify method. We always make call to identify with our ID, but users are still manage to make a purchase with anonymous ID somehow. That’s why we think we encounter these problems:
1. Users often loses a subscription until the purchase is restored. (Waiting for an alias to be created). We have a lot of reports from users on this.
2. Cross-platform subscription restoration doesn’t work. If user subscribed on Android, he can’t restore purchase on iOS, because SDK return no subscriptions for anonymous ID. But we always call Identify with our system ID first (ID is the same on both platforms)

**Comment by jeiting** [comment] 2020-07-06 14:36
If you are initializing the SDK without an app user id, and we're generating an anonymous ID for you, there will be instances where a purchase can happen before identify is called:

1. A renewal that happens on app launch, the transaction will occur immediately on SDK initialization, before you've passed your ID.
2. A purchase fails to validate, then SDK retries automatically on next launch on initialization

If you want to 100% prevent this from happening, you need to defer the call of setup() until you have your server provided app user id.

When you call `identify()` on top of an anonymous id, it will automatically alias the two users together. See here:
https://github.com/RevenueCat/purchases-ios/blob/develop/Purchases/Purchasing/RCIdentityManager.m#L53

I also think you are going to have problems if you are relying on `originalAppUserID`. The `originalAppUserID` will ALWAYS be the anonymous one in the setup you have described. The `originalAppUserID` will never change for a user, no matter how many identify or alias calls are made. What are you using `originalAppUserID`?

If you can provide me with the anonymous ID of an affected user, that would be helpful.

**Comment by sou1t** [comment] 2020-07-07 15:08
@jeiting Thanks for the detailed explanation, but I still don’t understand if this solves our problems. I remind you that we now have 2 main problems. The first is that users lose their subscription. The second is that cross-buying between platforms does not work. (Although a year ago we had no such problem in the project)

If I understand correctly, you suggest configuring ID with initializing the library. This approach does not suit us, I’m afraid that if we change the described logic to the proposed one, we may encounter side-effects of this transition in production.

Let me explain the logic by which we are working now. 
We have a container with services that is initialized with the launch of the application. When we initialize your library, there are two options. 
In the first case, the user is authorized in the application and during initialization we indicate our own ID. 
In the second case, the user is not authorized, his ID is unknown, SDK is initialized without ID. In this case, we use the identity method to indicate our own ID after authorization. 
To check an active sub we call .purchaserInfo closure at each restart of the application and on identify. There, we check that the array of active subscriptions is not empty.

This logic is the same for both platforms (iOS and Android).

I’m afraid that if we change the described logic to the proposed one, 100% of users will face the fact that they will lose their subscription. The restore will be needed.

I also want to give examples of users who have encountered problems.

$RCAnonymousID:d11ffd168c15407f92c736fa00a6fd73  OUR ID: cee7eda0-aa9f-44e9-9551-bf096c91fcac — This user made a purchase on Android, and now uses iOS and the purchase is not available to him.

$RCAnonymousID:9cee3a27b8e846669d5181a333d67f05  OUR ID: 29f26d34-da5a-488f-9f1e-efd37897e4db — This user paid for the subscription, but after some time he was faced with the fact that there is no active subs.

The main question is what are we doing wrong? Perhaps a mistake is on our side?

**Comment by leocassioo** [comment] 2020-07-07 18:31
@jeiting @aboedo What to do when multiple users can access the application from the same iPhone/device?

Even when performing `reset ()` and identifying the new user `identify ()` the data on the old user's server is overwritten when I make a purchase.

![Captura de Tela 2020-07-07 às 14 51 30](https://user-images.githubusercontent.com/16023720/86825274-8d1ded00-c065-11ea-99f3-e034dc82ff6c.png)

**Note that this user has just been created in our API, has no link with other users, just used the same iPhone.**

![Captura de Tela 2020-07-07 às 14 51 09](https://user-images.githubusercontent.com/16023720/86825296-927b3780-c065-11ea-81f0-3d0336b9505b.png)

**Complete user history exported from the RC panel**

[Customer 188.801.230-76 | RevenueCat.pdf](https://github.com/RevenueCat/purchases-ios/files/4886539/Customer.188.801.230-76.RevenueCat.pdf)

Some help? where am I wrong or is there a bug in the user defaults or RC/API?

In Android this does not happen at any time, I can use multiple accounts on the same device with the expected result.

**Comment by aboedo** [comment] 2020-07-07 21:02
@sou1t it looks like both of those users have purchases registered correctly, visible on the dashboard. 
Like Jacob said, the issue here might be a misunderstanding regarding the originalAppUserID - you don't really need it. 
Calling `identify` with your ID should return purchaserInfo that contains the purchases made by the user and any aliases they might have had. 
So in your case, when you call set up with no ID: 

1. RevenueCat generates anonymous ID `RCAnonymous123`
1. user makes a purchase
1. user authenticates as user `knownUser1`
1. your app calls `identify(knownUser)`, this generates an alias `RCAnonymous123` -> `knownUser1`. `knownUser1` is now entitled to any purchases made by `RCAnonymous123`. So the `purchaserInfo` returned by `identify` should contain entitlements for the purchases made in step 2.

This exact flow also applies if step 2 was performed on Android but steps 3 & 4 are performed on Android or on a new device. So `originalAppUserID` as a property shouldn't be needed at all. 

> Cross-platform subscription restoration doesn’t work. If user subscribed on Android, he can’t restore purchase on iOS, because SDK return no subscriptions for anonymous ID. But we always call Identify with our system ID first (ID is the same on both platforms)

I'm curious about this - does the purchaserInfo returned by identify in this case not contain the expected entitlements? 

> Users often loses a subscription until the purchase is restored. (Waiting for an alias to be created). We have a lot of reports from users on this.

This is the expected behavior on a fresh install, because we can't provide info on a user's purchases until they've been identified. However, subsequent app launches should already have the user's information stored. Is this not what you're seeing? If so, are you deleting user defaults by any chance or calling reset?

**Comment by aboedo** [comment] 2020-07-07 21:42
@leocassioo that alias is being created because the users are sharing the receipt, and two users can't share the same receipt in RevenueCat. 
There's a setting called `allowSharingAppStoreAccount`, which you can set to false, however what would happen if you do is that purchases made by the second user would still be attributed to the first one, and the second one would get an error. 
iOS unfortunately has no mechanism to separate the purchases into different receipts, and has no concept of sharing a device at the App Store Account level. We also don't have a way to programmatically get the iTunes account for the user, so there's not much that we can do there. 

Device sharing is fairly rare, so you likely don't need to worry about it.

**Comment by michaellenaghan** [comment] 2020-07-16 16:57
@aboedo what do you think of this scenario?

 * User has an iPhone.
 * User logs in to Apple using Apple ID a@example.com.
 * User runs app.
 * App initiailizes RevenueCat.
 * RevenueCat creates an anonymous user ID.
 * App associates (identifies) user with app-specific user ID aaa.
 * User makes a purchase in the app.
 * User logs out of Apple.
 * User logs in to Apple using Apple ID b@example.com.
 * User runs app.
 * App initiailizes RevenueCat.
 * RevenueCat recalls previous anonymous user ID from UserDefaults. (?)
 * App associates (identifies) user with app-specific user ID bbb.

Is that a possible scenario? If so, what happens next?

If RevenueCat generated an anonymous user ID, and if that user ID persisted across an iCloud/iTunes logout (is that possible?), would RevenueCat end up aliasing the two app IDs to the same anonymous ID, even though two different Apple accounts were involved? Because, of course, only one of those Apple accounts will have the actual purchase history.

(The kind of scenario I'm thinking about is something like "parent passes iPhone on to child, logs out but doesn't erase device.")

**Comment by aboedo** [comment] 2020-07-21 23:08
hey @michaellenaghan I'm sorry I missed this question. 
in your example, for the step 
```
RevenueCat recalls previous anonymous user ID from UserDefaults. (?)
```
the SDK wouldn't actually reuse an anonymous user ID. if the user is identified as `aaa`, the SDK will use `aaa` until either you `reset` or the app is uninstalled. if you call `identify` and your current user isn't anonymous (in this case, `aaa`), this will create an alias. 

so assuming that `reset` hasn't been called in the steps you wrote, you have
1. setup without passing id (anonymous id is created)
1. identify as aaa
1. purchase
1. setup without passing id (user is still aaa, read from user defaults)
1. identify as bbb (alias is created aaa -> bbb)

We don't have a way to programmatically check the App Store user, so we can't detect that the underlying credentials have changed. 
Since the underlying user has changed, a new receipt will be stored on the device, and it will contain the purchases made by `b@example.com` (in this case, no purchases). 

However, since the alias is there, bbb will be entitled to the purchases made by aaa. and if either of them make new purchases, they'll both own them, since they're the same user.

**Comment by michaellenaghan** [comment] 2020-07-22 00:35
OK, I think I understand.

Hopefully this is still in the general theme of this thread: I submitted a support request asking for clarification on `allowSharingAppStoreAccount`; I don't really grok the description given [here](https://github.com/RevenueCat/purchases-ios/blob/ecceef3e05edfd1b015ce41eb9a3208213447b77/Purchases/Public/RCPurchases.h#L183). (When I test restore I'm seeing [this](https://github.com/RevenueCat/purchases-ios/blob/8ceaca152c83bda4f19317e13db95000219b970e/Purchases/Public/RCPurchases.m#L624) message in the log.)

And kind of in the theme of this thread, though a little further afield: I am/was planning to use CloudKit user record IDs as my App User ID. But as I started testing I realized there's a problem: users can use separate iCloud and iTunes accounts on the same device. I'm trying to work through the implications of that.

For example, imagine someone is logged into iCloud *and* iTunes account `xxx`, and they subscribe. Now they change their iCloud account to `yyy`. With my current code, the new iCloud account means a new App User ID. Unless I do... something... I'll lose track of the fact that they already subscribed. (Of course, I could easily end up with the opposite problem, and associate accounts that shouldn't be associated.)

Good heavens.

You can see that all of this is connected.

Any insights?

**Comment by michaellenaghan** [comment] 2020-07-22 12:32
@aboedo Thinking about your response I think I see where I went wrong.

I thought that if I initially configured RC without an App User ID, and then identified the user later, the anonymous ID would be *the* App User ID, and my identifier would be an alias.

Thinking about your answer, and looking at the data in the RC dashboard, it seems that under certain circumstances the original anonymous App User ID can be forgotten, leaving only App User ID I passed in later.

I don't have a clear picture of what those circumstances would be. One theory: if you identify a user, and there's no transaction history for the anonymous App User ID, then the new App User ID replaces the anonymous one. (If there is transaction history, the new identifier becomes an alias of the original anonymous one.)

Is that in the ballpark?

Apologies for dragging this out; if I make mistakes on this they might be impossible to fix, so I'm trying to get it right.

PS I forgot to @mention you in the question above this one.

**Comment by michaellenaghan** [comment] 2020-07-22 18:49
@aboedo After thinking about this quite a bit I think I've realized that a) I probably shouldn't use iCloud user record IDs as my App User IDs***; and that b) I misunderstood how I might be able to take advantage of anonymous App User IDs. (I'm still thinking this through, but I currently have what I think is a simpler model in mind.)

*** The problem with using CloudKit user record IDs is that, as I said in an earlier comment, the user can change their iCloud and iTunes accounts independently—and, in the App Store, the subscription is really tied to the iTunes account rather than the iCloud account.

**Comment by aboedo** [comment] 2020-08-04 14:31
Hey @michaellenaghan I'm sorry for the (very) late response. 

Yeah, CloudKit user records IDs as app user IDs could be problematic, since it's independent from the iTunes account. It would be awesome if we had a way to fetch an id for the iTunes account, and it would certainly simplify a lot of these issues, but there's no way to do it as of right now. 

Anonymous IDs are meant to help in situations where you have an auth system and you want to be able to associate a user before and after they've logged in (for example, if you make a purchase and _then_ log in). 

They're also helpful if you don't have an auth system at all, since they at least provide _some_ way to identify the user. But if you don't have an auth system, then if a user moves to a new device, the only way to provide them with entitlements they had purchased on the previous device is to use `restoreTransactions`. 

> I thought that if I initially configured RC without an App User ID, and then identified the user later, the anonymous ID would be the App User ID, and my identifier would be an alias.
> 
> Thinking about your answer, and looking at the data in the RC dashboard, it seems that under certain circumstances the original anonymous App User ID can be forgotten, leaving only App User ID I passed in later.

I'm sorry if my response might have been confusing: the anonymous ID won't be forgotten, but it won't be picked up by the SDK, since the SDK will _replace_ the value in UserDefaults with the appUserID when you call identify (these are the calls to `clearCachesForAppUserID:andSaveNewUserID:` in `RCIdentityManager`. 
So the SDK won't see the anonymous ID anymore, but the backend will still store the anonymous ID. 

That said, anonymous IDs are meant for specific purposes, and you probably don't need to rely on them - if you have an accounts system, then those IDs should be the ones being used, and if you don't, then purchases will be retrievable by users by using `restoreTransactions`, and they'll retrieve whatever was bought with their iTunes ID.

**Comment by michaellenaghan** [comment] 2020-08-04 15:15
@aboedo Thanks. I did eventually figure all of that out, it just took a while. :-)

**Comment by aboedo** [comment] 2020-08-31 19:23
@michaellenaghan I'm closing this issue in that case, but feel free to reopen if anything else comes up.

**Closed by aboedo** 2020-08-31 19:23 UTC
