### ISSUE TITLE
didReceivePurchaserInfo is called every time the app launch

### ISSUE THREAD

**Issue by srgzah-ida** [RevenueCat/purchases-ios#262] opened 2020-06-18 14:03 UTC
Hello.
I use `didReceivePurchaserInfo` to track subscription updates.

According to the documentation [https://docs.revenuecat.com/docs/purchaserinfo#listening-for-purchaser-info-updates](https://docs.revenuecat.com/docs/purchaserinfo#listening-for-purchaser-info-updates).
This will fire whenever we receive a change in purchaser info on the current device.

But this method is called despite the absence of any changes.

**Comment by aboedo** [comment] 2020-06-18 15:03
Hi! I'm sorry for the confusion. 

That's actually the expected behavior:

> Since Purchases SDK works seamlessly on any platform, a user's purchase info may change from a variety of sources. You can respond to any changes in purchaser info by conforming to an optional delegate method, didReceivePurchaserInfo:. This will fire whenever we receive a change in purchaser info on the current device and you should expect it to be called at launch and throughout the life of the app.

Note the following line: "you should expect it to be called at launch". 

The reason is that since the purchaserInfo could have changed at any time between app opens, the SDK will always re-fetch it and doesn't store it locally, but rather only in memory.

**Comment by aboedo** [comment] 2020-06-18 17:35
Closing this as Not a Bug, but please feel free to check out [our support page](https://support.revenuecat.com) and contact support if you need further assistance.

**Closed by aboedo** 2020-06-18 17:35 UTC
