### ISSUE TITLE
Restore subscriptions cancel error.

### ISSUE THREAD

**Issue by pavelR** [RevenueCat/purchases-ios#83] opened 2019-02-08 16:22 UTC
I use Purchases (v 1.2.0) in my project. I can see the Purchases library sends the receipt data even if user cancels the subscription restore. In this case RevenueCat backend returns error:

` ("Error Domain=RCBackendErrorDomain Code=0 "The receipt is not valid." UserInfo= { NSLocalizedDescription=The receipt is not valid. }") `

and sends this error to delegate method. How can I distinguish between the case when user cancels restore subscription and the "real" backend error happens? Thanks!

**Comment by rkotzy** [comment] 2019-02-08 17:30
Hey @pavelR

Can you clarify what you mean by "user cancels the subscription restore"? Any reproducible steps you can provide will be helpful.

Since some issues are Sandbox specific, specifying what environment you encountered the issue could help. ​

Thanks!

**Comment by pavelR** [comment] 2019-02-11 11:45
> Hey @pavelR
> 
> Can you clarify what you mean by "user cancels the subscription restore"? Any reproducible steps you can provide will be helpful.
> 
> Since some issues are Sandbox specific, specifying what environment you encountered the issue could help. ​
> 
> Thanks!

Hi, thanks for quick response. There are steps to reproduce my problem:

**Precondition:** Sandbox user hasn't subscriptions in RevenueCat.

1. I call method `restoreTransactionsForAppStoreAccount()` when user tries to restore subscriptions.
2. Purchases framework shows alert with sign-in form to iTunes Store.
3. User press “Cancel” button.
4. I get described error in delegate method `purchases(_ purchases: RCPurchases, failedToRestoreTransactionsWithError error: Error)`.

Thanks.

**Comment by rkotzy** [comment] 2019-02-11 17:24
Thanks for the info, this is known behavior in Sandbox since there is no receipt on the device after an install - a backend error is thrown since an empty receipt is being sent to the server. In production you should always have a receipt file to restore with. 

I'm going to close this as an issue since and add it to the in-progress feature of "Overhaul SDK Error Handling" -> https://trello.com/c/CDm5Wxo8

**Closed by rkotzy** 2019-02-11 17:24 UTC

**Comment by pavelR** [comment] 2019-02-12 07:12
Thanks.
