### ISSUE TITLE
library not found for -lPurchases

### ISSUE THREAD

**Issue by deejay99** [RevenueCat/purchases-ios#169] opened 2020-02-02 01:44 UTC
Getting the following error when running the swift example app:

ld: warning: directory not found for option '-L/Users/Damian/Library/Developer/Xcode/DerivedData/SwiftExample-ezbgahlnwhanmghczzjmgcifqczs/Build/Products/Debug-iphoneos/Purchases'
ld: library not found for -lPurchases
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by aboedo** [comment] 2020-02-03 14:27
Hi @deejay99, 

Thanks for reporting. 

I just tried a clean clone of the project, and I couldn't reproduce this - it worked correctly for me. 
I downloaded the project, opened the swift example, `pod install`, replaced the API key and ran, both on physical device and on simulator, no issues. 

Could you provide more detail for your steps? 

Is `libPods-SwiftExample.a` listed in "Link Binary With Libraries" in the Build Phases for the Swift Example target? 
Also, is `[CP] Check Pods Manifest.lock` build step in Build Phases?

**Comment by deejay99** [comment] 2020-02-03 15:31
Hi

Figured it out in the meantime, was accidentally working formt he xcodeproj instead of the xcworkspace so the pod folder was not included… works well now.

Best,
Damian

**Comment by aboedo** [comment] 2020-02-03 15:56
cool, glad it worked 👍. I'll close the issue

**Closed by aboedo** 2020-02-03 15:56 UTC
