### ISSUE TITLE
iOS Swift: Where should I put a spinner to show loading during purchase and restore purchase process?

### ISSUE THREAD

**Issue by Haibo-Zhou** [RevenueCat/purchases-ios#734] opened 2021-08-12 07:49 UTC
Hello I integrated your sdk in my iOS app, it is working now. 

I want to show a spinner to tell user their purchase is processing because sometimes the processing time is long. I have no clue where I should put it in? First I try to implement protocol `SKPaymentTransactionObserver`, but its protocol method like `paymentQueue(_ queue: SKPaymentQueue, updatedTransactions...` is not triggered when purchase is fired.

Below is my purchase function in Swift, I put a spinner in it. But not sure if it is the correct place. Please help, Revenue Cat.

If this is not the case, then what is the correct behavior for app when a user press purchase or restore button?

```
    func purchase(package: Purchases.Package) {
        Purchases.shared.purchasePackage(package) { [weak self] transaction, info, error, userCancelled in
            guard let _ = transaction,
                  let info = info,
                  error == nil, !userCancelled else { return }
            DispatchQueue.main.async {
                self?.showSpinner()
            }
            
            if info.entitlements.all["Premium"]?.isActive == true {
                // save user state
                KeychainWrapper.standard.set(true, forKey: "isPremium")
                // remove interstitial ads
                GoogleAdMob.shared.interstitial = nil
                print(" 👠 Purchase OK")
                DispatchQueue.main.async {
                    // show hide UI elements

                    self?.removeSpinner()
                }
            }
            else {
                DispatchQueue.main.async {
                    // show hide UI elements
                    
                    self?.removeSpinner()
                }
            }
        }
    }
```

**Comment by aboedo** [comment] 2021-08-12 18:43
Hey @Haibo-Zhou!! 👋 

For a spinner or any kind of loading state, you'll want to make sure that the spinner is shown _before_ you call the methods in `Purchases`, and it's removed in the completion block. 

In your example: 

```swift
func purchase(package: Purchases.Package) {
    self.showSpinner()
    Purchases.shared.purchasePackage(package) { [weak self] transaction, info, error, userCancelled in
        DispatchQueue.main.async {
            self.removeSpinner()
        }
        guard let _ = transaction,
              let info = info,
              error == nil, !userCancelled else { return }
        // rest of the code
```

important bits are: 
- show spinner _before_ the asynchronous code starts
- remove it in the main thread
- you can have the remove spinner block happen at the end of the completion method too, which might be useful if you want to make sure you only remove the loading spinner once all operations are done. [You can even use](https://www.hackingwithswift.com/new-syntax-swift-2-defer) a `defer` for that. 

We reserve GitHub issues for bug reports only. The best place to get help for this kind of thing is: 
- [The RevenueCat community](https://community.revenuecat.com/)
- [Our docs](https://docs.revenuecat.com/docs) for setup information and code samples
- [Our example apps](https://github.com/RevenueCat/purchases-ios/tree/main/Examples)

Hope this helps!! 

I'm closing out this issue since it's not a bug report. 

Have a great day!

**Closed by aboedo** 2021-08-12 18:43 UTC
Labels: bug

**Comment by Haibo-Zhou** [comment] 2021-08-13 04:14
@aboedo, thanks for the quick & detailed reply.
I will have a try on both approaches. And yeah, next time I would go to your community for a question. Have a nice day!

**Comment by aboedo** [comment] 2021-08-13 14:19
yeah, that makes sense. That's a part of how DispatchQueue async works - it will save a work task to do once the thread is free, but it won't execute until that point. If you need it to happen right away, you'd have to use `sync`, but be warned that that may lead to issues like deadlocks, so for something like this, async would do the trick just fine without any risks.
