### ISSUE TITLE
`Purchases.shared.purchase(package: ) async` not being called when the user cancels

### ISSUE THREAD

**Issue by jhoanarango** [RevenueCat/purchases-ios#1445] opened 2022-04-05 06:23 UTC
- [✅] I have updated Purchases SDK to the latest version
- [✅] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [✅] I have searched the [Community](https://community.revenuecat.com)
- [✅] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [✅] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**

While doing a test purchase, I noticed that when cancelling the purchase, the Purchases.shared.purchase(package:) async does not return PurchaseResultData.userCancelled. It simply does nothing. 

Making the purchase works as expected, but not when the user cancels.

Link to the method being used.
[https://revenuecat-docs.netlify.app/documentation/revenuecat/purchases/purchase(package:)](url)

1. Environment
   1. Platform: Apple/iOS
   2. SDK version: 4.1.0
   3. OS version: 
   4. Xcode version: 13.3
   5. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

<img width="1182" alt="Screen Shot 2022-04-05 at 2 14 08 AM" src="https://user-images.githubusercontent.com/14069813/161690502-51b1725a-99aa-43ce-b3b9-75c9c602c8ec.png">

**Comment by NachoSoto** [comment] 2022-04-05 16:09
Thanks for taking the time to file an issue! I'm looking into this right now.
Could you let us know if you have StoreKit 2 enabled? If you're not sure then the answer is probably no [since it's currently opt-in only](https://github.com/RevenueCat/purchases-ios/blob/main/Sources/Purchasing/Purchases.swift#L1745).

**Comment by NachoSoto** [comment] 2022-04-05 16:11
Also wondering if you're seeing this issue in the simulator and/or on devices.

**Comment by jhoanarango** [comment] 2022-04-05 16:13
Hey, 

So the test are being done in an actual device and not in the simulator, and for your first question the answer would be "I'm not sure". I will check that right now and get back to you if opting-in will make any difference.

**Comment by NachoSoto** [comment] 2022-04-05 16:14
> So the test are being done in an actual device and not in the simulator,

Okay thanks that helps. Taking a look right now.

**Comment by jhoanarango** [comment] 2022-04-05 16:31
@NachoSoto

Did the test with opting-in to StoreKit 2 and that worked, went back to opting-out and it didn't work. I did get this log when testing as not opt-in for StoreKit 2. 

"["NSUnderlyingError": Error Domain=ASDErrorDomain Code=907 "Unhandled exception" UserInfo={NSUnderlyingError=0x2833cdd70 {Error Domain=AMSErrorDomain Code=6 "Payment Sheet Failed" UserInfo={NSLocalizedFailureReason=Payment sheet cancelled, AMSURL=https://sandbox.itunes.apple.com/WebObjects/MZBuy.woa/wa/inAppBuy?guid=00008110-000631101A84801E, AMSStatusCode=200, AMSServerPayload_desc={
    "cancel-purchase-batch" = 1;
    customerMessage = "Sign in with Apple ID";
    dialog =     {
        cancelButtonString = Cancel;
        defaultButton = Buy;
        explanation = "Enter the password for %%appleId%% to authorize this transaction.\n\n[Environment: Sandbox]";
        initialCheckboxValue = 1;
        kind = authorization;
        "m-allowed" = 0;
        message = "Sign in with Apple ID";
        okButtonAction =         {
            buyPara
"

Not sure if that would help, of if this code is only meant to be used with StoreKit 2.

**Comment by NachoSoto** [comment] 2022-04-05 16:40
> Did the test with opting-in to StoreKit 2 and that worked, went back to opting-out and it didn't work. 

Cool yeah so this is only an issue on StoreKit 1.

> I did get this log when testing as not opt-in for StoreKit 2.

And this is why I'll never stop complaining about untyped errors being a problem 😄 
So it looks like `StoreKit` is internally reporting the cancellation, but something changed in iOS (this looks like a regression) and they're not handling that error, and instead reporting "unhandled exception". 
Actually looks like that's the `NSUnderlyingError`, what's the top error that's being logged?

> Not sure if that would help, or if this code is only meant to be used with StoreKit 2.
> Better question is: Is V4.1 meant to be used with StoreKit 2 ?

The SDK supports both StoreKit 1 and 2. SK2 support is still experimental since it was rolled out very recently, so it's perfectly fine to continue using the SDK with SK1. SK2 is of course the future, and will be better supported by Apple in the future.

Let me try to reproduce this on a device (I was checking this in the test environment) and see if we could add a workaround for it. In the mean time, you might want to enable SK2 to fix this.

**Comment by jhoanarango** [comment] 2022-04-05 16:51
> what's the top error that's being logged?

This is what I get.

2022-04-05 12:46:11.105758-0400 Crewline[3599:264856] <SKPaymentQueue: 0x280855e50>: Payment completed with error: Error Domain=ASDErrorDomain Code=907 "Unhandled exception" UserInfo={NSUnderlyingError=0x2805c00c0 {Error Domain=AMSErrorDomain Code=6 "Payment Sheet Failed" UserInfo={NSLocalizedFailureReason=Payment sheet cancelled, AMSURL=https://sandbox.itunes.apple.com/WebObjects/MZBuy.woa/wa/inAppBuy?guid=00008110-000631101A84801E, AMSStatusCode=200, AMSServerPayload_desc={
    "cancel-purchase-batch" = 1;
    customerMessage = "Sign in with Apple ID";
    dialog =     {
        cancelButtonString = Cancel;
        defaultButton = Buy;
        explanation = "Enter the password for %%appleId%% to authorize this transaction.\n\n[Environment: Sandbox]";
        initialCheckboxValue = 1;
        kind = authorization;
        "m-allowed" = 0;
        message = "Sign in with Apple ID";
        okButtonAction =         {
            buyParams = "hasFailedTouchIDChallenge=true&salableAdamId=1547086497&showIAPExtraDialog=false&applicationUsername=CPLwj7mX4lW7N6g34rQaqrLWHxA2&offerName=com.crewlineapp.com_firstclass_monthly&productType=A&hasBeenAuthedForBuy=true&quantity=1&price=2990&hasConfirmedBuySubscription=true&ageCheck=true&pricingParameters=STDQ&vid=D06D8875-8ABF-4E1F-8C45-8E41CFE95D4F&bvrs=0&pg=default&hasConfirmedPaymentSheet=true&bid=com.paytrackapp.crewline&hasWebOptIn=false";
            itemName = "com.crewlineapp.com_firstclass_monthly";
            kind = Buy;
        };
        okButtonString = Continue;
        paymentSheetInfo =         {
            caseControl = true;
            confirmationTitle = Subscribe;
            countryCode = US;
            currency = USD;
            flexList =             (
                                {
                    header = DETAILS;
                    value = "For testing purposes only. You will not be charged for confirming this purchase.";
                },
                                {
                    header = ACCOUNT;
                    value = "%%appleId%%";
                },
                                {
                    attributedList =                     {
                        value =                         (
                                                        {
                                header = PRICE;
                                value =                                 {
                                    size = large;
                                    value = "$2.99 per month";
                                };
                            }
                        );
                    };
                }
            );
            images =             (
                                {
                    type = itunesgames;
                    value = "4+";
                }
            );
            isLastElementPinned = 1;
            paymentSummary = PRICE;
            requestor = AppStore;
            salableIcon = "https://is2-ssl.mzstatic.com/image/thumb/Purple126/v4/59/0a/68/590a684b-39c9-f0c1-4e4c-314b0aa543bd/AppIcon-0-1x_U007emarketing-0-7-0-85-220.png/144x144bb.jpg";
            salableIconType = app;
            salableInfo =             (
                "First Class Monthly %%image_0%%",
                Crewline,
                Subscription
            );
            title =             {
                type = text;
                value = Sandbox;
            };
        };
    };
    failureType = "";
    "m-allowed" = 0;
    metrics =     {
        actionUrl = "sandbox.itunes.apple.com/WebObjects/MZBuy.woa/wa/inAppBuy";
        dialogId = "MZCommerceInAppBuy.ConfirmationNeededForBuyRecurringItem.CPS.Auth";
        eventType = dialog;
        message = "Sign in with Apple ID";
        mtEventTime = "2022-04-05 16:46:05 Etc/GMT";
        osloTitleType = text;
        osloTitleValue = "AbstractSalableInfoModule.SandboxTitle";
    };
    pings =     (
        "https://xp.apple.com/report/2/xp_its_main?code=MZCommerceInAppBuy.ConfirmationNeededForBuyRecurringItem.CPS.Auth&buttons=Continue%3ACancel&baseVersion=1&dsId=20138554846&eventVersion=1&storeFrontHeader=143441-1%2C29&eventTime=1649177167711&eventType=dialog&message=Sign%20in%20with%20Apple%20ID"
    );
}, NSLocalizedDescription=Payment Sheet Failed}}, NSLocalizedFailureReason=An unknown error occurred, NSLocalizedDescription=Unhandled exception}

**Comment by NachoSoto** [comment] 2022-04-05 16:59
Okay thanks! I'll send a PR in a few minutes with a proposed patch for this.

**Comment by NachoSoto** [comment] 2022-04-05 17:16
Proposed solution: #1450

**Comment by jhoanarango** [comment] 2022-04-05 17:21
@NachoSoto, Thank you for your speedy response to this issue and propose fix.

**Comment by NachoSoto** [comment] 2022-04-05 17:25
My pleasure!

I forgot the address the "not being called when the user cancels" portion. The reason for that is that your `Task` is throwing an exception (in this case, the unknown error). Of course you expected that to return a result with `cancelled = true`, but if any other errors are thrown your code is currently ignoring them.

To prevent that, I recommend using defining the task as such:
```swift
_ = Task<Void, Never> {
  do {
    // Your code here
  } catch {
    // The compiler will not require to catch exceptions
  }
}

**Comment by jhoanarango** [comment] 2022-04-05 18:09
Thank you, makes sense. After all this time I am just getting familiarized with swift new cuncurrency.

**Comment by NachoSoto** [comment] 2022-04-05 20:20
Fix is in `main`, thanks again for reporting this!

**Closed** 2022-04-05 20:20 UTC
Labels: bug
