### ISSUE TITLE
[macOS] Purchases.purchasePackage returns userCancelled == false when clicking on Cancel in Confirm Subscription popup

### ISSUE THREAD

**Issue by iPile** [RevenueCat/purchases-ios#370] opened 2020-10-14 08:26 UTC
## Common project specific issues

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue.

1. Environment
    1. Platform: macOS 
    2. SDK version: 10.15.6 (19G68)
    3. OS version: Big Sur - 11.0 Beta (20A5384c)
    4. Xcode version: 12.0.1
    5. How widespread is the issue. 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) 

`<SKPaymentQueue: 0x6000015cd740>: Payment completed with error: Error Domain=ASDServerErrorDomain Code=5115 "The server encountered an error" UserInfo={NSLocalizedDescription=The server encountered an error}
[Purchases] - DEBUG: PaymentQueue updatedTransaction: P1Y.mac_app_store_trial_1 (null) (Error Domain=SKErrorDomain Code=0 "UNKNOWN_ERROR" UserInfo={NSLocalizedDescription=UNKNOWN_ERROR, NSUnderlyingError=0x6000018cd260 {Error Domain=ASDServerErrorDomain Code=5115 "The server encountered an error" UserInfo={NSLocalizedDescription=The server encountered an error}}}) (null) - 2
[Purchases] - ERROR: There was a problem with the App Store.`

3. Steps to reproduce, with a description of expected vs. actual behavior

#### Steps to reproduce: 
1. Click on Cancel in either the Subscription Terms screen or Confirm Subscription screen 

![image](https://user-images.githubusercontent.com/43062515/95954128-81c82380-0e03-11eb-82ad-193182ae5939.png)

![image](https://user-images.githubusercontent.com/43062515/95954202-9ad0d480-0e03-11eb-9a6a-36827421a943.png)

#### Expected outcome:

- Returns 'userCancelled == true'

#### Actual:

- Returns `userCancelled == false` and error:

![image](https://user-images.githubusercontent.com/43062515/95954371-dd92ac80-0e03-11eb-9037-d80e35e66c90.png)

**Comment by rkotzy** [comment] 2020-10-14 23:25
Are you able to reproduce this with a fresh sandbox user? It looks like there may be some leftover transactions on the payment queue that may be interfering with this new purchase.

e.g. `DEBUG: PaymentQueue updatedTransaction: P1Y.mac_app_store_trial_1 `

**Comment by ignalonzo** [comment] 2020-10-15 06:27
The screenshots attached and the debug messages were received with a fresh sandbox user. 

To confirm I have just tried one more time, cleaned XCode cache, created a new sandbox user - same result.

`[Purchases] - DEBUG: PaymentQueue removedTransaction: P1Y.mac_app_store_trial_1 (null) ((null) Error Domain=SKErrorDomain Code=0 "UNKNOWN_ERROR" UserInfo={NSLocalizedDescription=UNKNOWN_ERROR, NSUnderlyingError=0x600003c3e190 {Error Domain=ASDServerErrorDomain Code=5115 "The server encountered an error" UserInfo={NSLocalizedDescription=The server encountered an error}}}) {
    NSLocalizedDescription = "UNKNOWN_ERROR";
    NSUnderlyingError = "Error Domain=ASDServerErrorDomain Code=5115 \"The server encountered an error\" UserInfo={NSLocalizedDescription=The server encountered an error}";`

**Comment by rkotzy** [comment] 2020-10-15 14:07
Are you using StoreKit.config files for testing? If so, those files aren't supported yet but will be soon.

**Comment by ignalonzo** [comment] 2020-10-16 11:04
No, we're just using Sandbox testing on all macOS versions (we support from 10.13) and StoreKit.config is supported only from macOS 10.15

This issue is reproducible only on Big Sur Beta

**Comment by aboedo** [comment] 2020-10-19 15:19
I wonder if this might be an issue of Big Sur Beta's IAPs in that case. We'll check it out

**Comment by ignalonzo** [comment] 2020-10-23 12:12
Bump, any luck guys?

**Comment by rkotzy** [comment] 2020-10-28 17:14
@ignalonzo we are seeing the same error here when the payment sheet is cancelled. Unfortunately I don't think there's any workaround since the wrong error message is coming from Apple. Hopefully this is a quirk of Big Sur Beta and it's fixed before the official release. We can keep the issue open to track any updates.

**Comment by aboedo** [comment] 2020-11-16 16:47
@ignalonzo 
update here: just tried this out on Big Sur 11.0.1, and I was able to make a successful purchase, with no errors. 

If I try to purchase the same product again while the subscription is active, though, I do get a similar traceback as you did, stemming from a 500 error from App Store. 

Is this still happening to you on 11.0.1?

**Comment by ignalonzo** [comment] 2020-11-24 09:35
Hey, @aboedo , thanks for the response. 

The problem surfaces not when making a purchase, but when you cancel the purchase. Then, the `userCancelled` completion returns `false`, when it should return `true` (at least it does on Catalina). 

The problem is still there for us on 11.0.1

**Comment by rkotzy** [comment] 2020-11-25 00:27
As long as StoreKit is returning `SKErrorDomain Code=0 "UNKNOWN_ERROR"`, there unfortunately isn't a way to tell if the user cancelled the payment flow or not. Apple is supposed to be returning [SKErrorDomain Code=2](https://developer.apple.com/documentation/storekit/skerror/code/paymentcancelled) indicating a cancellation. Going to chalk this up as a macOS bug, we can keep the issue around for discussion.

**Comment by taquitos** [comment] 2021-11-09 22:24
We can't guess what happened, but we can surface more than the error by saying "This is an error, but it might be a user cancellation, unfortunately there's no reliable way to know" something like that, I'm terrible with words.

**Comment by NachoSoto** [comment] 2021-11-15 20:30
I can confirm this is still an issue on macOS 12.0.1. I just filed a Feedback with Apple: `FB9761183`.

**Comment by NachoSoto** [comment] 2021-11-15 20:39
I just submitted my proposed change: #943.

**Comment by NachoSoto** [comment] 2021-11-15 20:50
By the way I confirmed this only seems to affect `macOS`. `iOS` does correctly result in `ErrorCode.purchaseCancelledError`.

**Comment by NachoSoto** [comment] 2021-11-15 21:38
Should we close this for the time being? I will report back if Apple replies to my Feedback (LOL)

**Closed** 2021-11-16 00:25 UTC
Labels: sharpen the saw, triaged

**Comment by NachoSoto** [comment] 2021-12-14 20:08
I just filed another Feedback because the same error is reproducible on Store Kit 2: FB9808927
Unfortunately `StoreKitError` has no underlying error information, so we won't be able to work around this as we did on #965.

But I'm opening a PR to at least provide the same error message in #943.

**Comment by NachoSoto** [comment] 2023-01-23 03:51
Looks like this may have been fixed in macOS 12.1
