### ISSUE TITLE
Is there a delegate for handling AppStore Promo Code?

### ISSUE THREAD

**Issue by Kalzem** [RevenueCat/purchases-ios#235] opened 2020-05-07 17:01 UTC
I would like to hand to my users promo code that unlocks consumables IAP (on iOS) as detailed by Apple here: https://help.apple.com/app-store-connect/#/dev50869de4a

However, I do not see any "listeners" on RCPurchasesDelegate.

How can I handle this case?

**Comment by aboedo** [comment] 2020-05-07 17:48
You can use the `RCPurchasesDelegate`: 
- Create a class that implements the `RCPurchasesDelegate` protocol
- call `Purchases.shared.delegate = yourObject`
You'll get a callback when new purchaser info is available, and also when a user makes purchases through App Store. 

More info: 
https://sdk.revenuecat.com/ios/Protocols/RCPurchasesDelegate.html#/c:objc(pl)RCPurchasesDelegate(im)purchases:didReceiveUpdatedPurchaserInfo:

**Comment by Kalzem** [comment] 2020-05-07 18:09
Thanks for the reply.

I have already implemented this protocol and it doesn't seem to do anything.

I am talking about Promo Code (to redeem a IAP), not Promotional purchase through the App Store (which is already implemented and works on my production app).

Also I have looked into the SDK code, and it doesn't seem like my situation is hooked into the protocol.

The protocol only triggeres through `paymentQueue:shouldAddStorePayment:` whereas Promo Code triggers an `paymentQueue:updatedTransactions:`

**Comment by Kalzem** [comment] 2020-05-07 18:33
Looking deeper into the SDK, I really don't see this feature being handled.

Promo Code redeemed on iOS generates a transaction on Apple servers (independently from the app). Upon opening the app, it will fire a `paymentQueue:updatedTransactions:`.

Now the issue with RevenueCat is that once the flow is completed in

`RCPurchases.m > handlePurchasedTransaction: > handleReceiptPostWithTransaction:purchaserInfo:subscriberAttributes:error:`

it will only trigger callbacks (`purchaseCompleteCallbacks`) and update userInfo (which doesn't contain enough info to guess that a Promo Code was used once).

I believe RevenueCat needs to plug a new optional func in the `RCPurchasesDelegate` protocol such as 
`func handleOther(_ purchases: Purchases, didPurchaseProduct product: SKProduct)`

And this optional function is only called if a completion is nil in `self.purchaseCompleteCallbacks[transaction.payment.productIdentifier]`, so that wee don't have a logic fired twice from the completion AND from the implemented delegate.

Unless I'm unaware of a flag that states "is_promo_code" from the Receipt, in which case we can have a more explicit new optional func in the protocol `func handlePromoCode(_ purchases: Purchases, forProduct product: SKProduct)`.

Currently, RevenueCat will complete all promo codes transactions without being consumed on the client side correctly, and these promo codes can't be restored (in the case of consumable IAP). Which is actually a buggy situation 😭

**Comment by aboedo** [comment] 2020-05-09 00:30
hey @Kalzem ,

There's no real way to distinguish promo code redemption from a regular purchase. So it wouldn't be possible for the SDK to provide a separate method for them. 

The expected behavior for promo codes is: 
- User redeems promo code
- It gets added to the queue and treated the same as if the user had just made a purchase on the app
- The receipt is sent to our server for validation, once validation is cleared, purchaserInfo is updated and the delegate method is called with new purchaserInfo. 

It sounds like this isn't what you're seeing, so we're going to do more testing on our side to see if we can reproduce and I'll update the ticket when I know more.

**Comment by Kalzem** [comment] 2020-05-09 07:48
The keyword that changes everything is **consumable** IAP, as they don't appear in the purchaserInfo. For non-consumable, there is no problem, I can retrieve entitlements from the purchaserInfo.

I understand that you don't have a way to distinguish promo codes from regular purchases. That's why I suggested a protocol method that is triggered for all non-registered purchases.
Any `paymentQueue:updatedTransactions:` that doesn't originally come from RevenueCat SDK `purchaseProduct:` or `purchasePackage:` can trigger a new protocol (optional) method `unhandledPurchase:` for example.

**Comment by rkotzy** [comment] 2020-05-11 23:02
There is an NSSet of `allPurchasedProductIdentifiers` available in PurchaserInfo. But the issue here is you can't determine how many times a consumable was purchased and if you've handled it on your backed. Doesn't seem as related to promo codes and more with how consumables are handled - does that seem correct?

A solution could be to expose an array of purchased non-subscription identifiers, similar to the Non-Subscription object that's already sent down in the REST API: https://docs.revenuecat.com/reference#the-non-subscription-object

**Comment by Kalzem** [comment] 2020-05-12 07:18
Thanks for the reply.

But I'm not sure we are talking about the same issue.

My initial issue is that: RevenueCat consumes iOS Promo Code of **consummable** IAP without telling the developers. The promo code is therefore "successfully used" from RevenueCat's perspective, but fails from the users' perspective (because, as developers, we have no idea that a promo code was used and we cannot give "100 coins" or so to the users).

There are different approaches to solve this issue, and "enhancing" the data in PurchaserInfo isn't one IMHO because, let's say you inject in it a complete purchase history with all products identifiers and the timestamp of each purchases and so on, then it means that we need to keep our own version of what we already served to the users (in order to not unlock twice the benefits of a consummable). It increases the complexity of using RevenueCat.

**Comment by aboedo** [comment] 2020-05-14 20:43
We currently don't have support for marking consumable purchases as "consumed" or "redeemed", keeping inventory on the RevenueCat side. 
This is however something that we're considering, to make life easiers for developers who rely on consumables. 

Like @rkotzy mentioned, a first step toward that will be to improve the way that we present the consumables in the SDK so that we use an array instead of an set, allowing for devs to do the inventory on their side.

**Comment by Kalzem** [comment] 2020-05-15 08:45
Hmmm, I admit that I feel a bit lost.

Did you try the scenario (redeeming a promo code of a consumable IAP) on one of your apps?

I don't see how getting an array/set/dictionary of consumables IAP will help me understand that a promo code was just redeemed.

I might be missing something here. Can you explain how you expect us to detect this promo code then "unlock the 100 coins" (or whatever benefits) to the final users?

Currently to do this with an actual consumable purchase (not a promo code), we are supposed to do something like this (right?) :

```swift
Purchases.shared.purchaseProduct(productId) { transaction, info, error, cancelled in
  if let error = error {
    // Handle error
  } else {
    // Unlock benefits of productId (such as 100 in-game coins)
  }
}
```

So why can't we get something like this:

```swift
Purchases.shared.unhandledPurchaseWhichMightBeAPromoCode() { *PRODUCT_ID*, transaction, info, error in
  if let error = error {
    // Handle error
  } else {
    // Unlock benefits of PRODUCT_ID (from callback parameter)
  }
}
```

or as a delegate function

```swift
class MyManager: PurchasesDelegate {
  func unhandledPurchasesWhichMightBeAPromoCode(productId: String, _ purchases: Purchases, ...) {
    if let error = error {
      // Handle error
    } else {
      // Unlock benefits of PRODUCT_ID (from callback parameter)
    }
  }
}
```

**Comment by aboedo** [comment] 2020-05-15 19:32
`RCPurchasesDelegate` implements something similar to what you've described. Here's the expected flow: 
- user redeems promo code
- payment is added to the queue
- SDK processes the transaction, reads receipt, sends to the backend for storage
- Backend acknowledges the purchase and adds it to purchaserInfo
- SDK receives updated purchaserInfo, communicates that to the delegate
- Delegate looks at the `allPurchasedProductIdentifiers` in purchaserInfo, and checks whether the productId was redeemed (along with any other purchases that the user might have made with the app closed, like subscription renewals and such). 

So you'd have something like: 

```swift
class MyClass: PurchasesDelegate {
     func purchases(_ purchases: Purchases, didReceiveUpdated purchaserInfo: Purchases.PurchaserInfo) {
        // your app keeps inventory of the things you know the user bought
        let redeemedPurchasedProductIdentifiers = myApp.redeemedPurchasedProductIdentifiers()
        
        // RevenueCat knows the full set of everything the user ever bought
        let allPurchasedProductIdentifiers = purchaserInfo.allPurchasedProductIdentifiers
        let allPurchasedProductIdentifiersList = Array(allPurchasedProductIdentifiers)
        
        // you compare to see if there's anything that the user bought but you haven't redeemed yet
        let newlyPurchasedProductIdentifiers = findNewProductIdentifiers(allPurchasedProductIdentifiersList, redeemedPurchasedProductIdentifiers)

        // you provide the users with their redeemed stuff and update your list of redeemed products
        redeemProductIdentifiers(newlyPurchasedProductIdentifiers)
    }
```

The thing that doesn't work great currently and we'll improve in the next SDK version is the fact that `allPurchasedProductIdentifiers` is a set, so it will remove duplicates and thus make it impossible to determine if a product has been purchased more than once from the SDK (the API does show it as a list with duplicates, though). We'll move that to a list very soon so that this is no longer an issue. 

As I said before, we're considering keeping track of what has been redeemed on the app side somewhere down the line, but as of right now your app would have to do it. This is what `myApp.redeemedPurchasedProductIdentifiers()` represents in the example above. 

Hope that helps clear things up!

**Comment by Kalzem** [comment] 2020-05-16 08:39
Thanks for the explanation. 

With this approach, it means that the SDK clients must indeed record which transaction has been delivered to the end user or not. AND synchronize these records online to handle users with multiple devices (so that they don't get twice a consumable IAP on their different devices). At least, until RevenueCat handles these records.

Do you have a vague date estimation for this feature? (Next month, this summer, end of year, next year?)

**Comment by aboedo** [comment] 2020-05-22 14:31
I don't have an ETA for this feature, I'm afraid. It's in our roadmap, but we have a few items in our backlog that we need to take care of first. 

I'm closing this issue for now since we try to reserve GitHub Issues for bug reports. 

Thanks for the patience and for the communication on this one, it'll help shape the feature when it gets developed.

**Closed by aboedo** 2020-05-22 14:31 UTC
