### ISSUE TITLE
Swift Package Manager: 'RCDeviceCache.h' file not found

### ISSUE THREAD

**Issue by blainesolomon** [RevenueCat/purchases-ios#176] opened 2020-02-09 00:02 UTC
Everything was working well until I opened the project today. Looks like it's running 3.0.3 now.

**Comment by andreagelati** [comment] 2020-02-10 08:34
I have the same issue with 3.0.3... 'RCDeviceCache.h' file not found

**Comment by aboedo** [comment] 2020-02-10 12:54
I'll check it out. Are you using Cocoapods?

**Comment by aboedo** [comment] 2020-02-10 13:30
I just tried installing 3.0.3 on a clean project with Cocoapods and it seems to work correctly. 
There was some reorganization of files for 3.0.3, which involved updating `source_files` in the Podspec. 
This seems like a likely culprit. 
`RCDeviceCache.h` was moved into a group, so my thinking is that there might be something cached on your computer that would prevent Cocoapods from realizing that it needs to get `RCDeviceCache.h` from the new group, instead of the old one. 
I'll do some more local testing to see if I can repro your case, but in the meantime, maybe 
```
pod cache clean 'Purchases' --all
```
helps?

**Comment by aboedo** [comment] 2020-02-10 13:48
update: I managed to reproduce with swift package manager, I'll dig around to see what the problem is

**Comment by aboedo** [comment] 2020-02-10 14:27
I made a fix for it, PR: https://github.com/RevenueCat/purchases-ios/pull/177

Once the PR gets merged, it'll be available as version 3.0.4. 
In the meantime, you can either downgrade to 3.0.2 or set the Version Rules to the fix branch, `fix/swift_package_manager_missing_cache_group`. 

<img width="1014" alt="Screen Shot 2020-02-10 at 11 26 13 AM" src="https://user-images.githubusercontent.com/3922667/74158065-2d2b3380-4bf8-11ea-8f45-fb1026b90c1a.png">
<img width="487" alt="Screen Shot 2020-02-10 at 11 26 18 AM" src="https://user-images.githubusercontent.com/3922667/74158083-35836e80-4bf8-11ea-9964-b999341bc11d.png">

@blainesolomon @andreagelati thanks for reporting!! Let me know if this works.

**Comment by aboedo** [comment] 2020-02-17 14:23
version 3.0.4 is out and it includes the fix for this. Check it out! 
Thanks again for reporting!

**Comment by andreagelati** [comment] 2020-02-19 11:01
Thank you @aboedo, I have updated to version 3.0.4 and I can confirm the issue is fixed. 👍

**Comment by aboedo** [comment] 2020-02-19 12:36
awesome! glad it's working now 👍

**Closed by aboedo** 2020-02-19 12:36 UTC
