### ISSUE TITLE
AppStore.showManageSubscriptions(in: scene) Freezes App When Dismissed

### ISSUE THREAD

**Issue by haarj** [RevenueCat/purchases-ios#1270] opened 2022-02-08 09:02 UTC
This isn't a RevenueCat bug but I tried using this API on simulator and device and whenever I dismiss the in-app subscription management page by pressing the page's "X" button on the top right, the app gets stuck. In fact, any iPhone with a notch gets bricked, lol. Just wondering if you experienced this too. 

1. Environment
   1. Platform: iOS
   2. SDK version: NA
   3. OS version: 15.3
   4. Xcode version: 13.2.1
   5. How widespread is the issue. Percentage of devices affected. NA
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by aboedo** [comment] 2022-02-09 19:31
I haven't experienced any issues with it so far. 

I just did a sanity check: 
iOS 15 simulator
https://user-images.githubusercontent.com/3922667/153275899-ae2c1fe5-2c98-4770-a833-35cb3d7daac7.mp4

iOS 15.4 (beta) physical device
https://user-images.githubusercontent.com/3922667/153275956-d7b29b5d-75b2-4c69-ad4f-dccbf07c9512.mov

Is there anything that looks relevant in the debug logs? 

Are you using a Storekit Configuration file?

**Comment by haarj** [comment] 2022-02-09 21:17
Nothing in the logs and yea I used a store kit config file. Any recommendation on which windowScene to use? I’m using the one from the view controller I’m presenting it from.

Justin
646-334-3312

**Comment by aboedo** [comment] 2022-02-10 14:18
I'm using the [`currentWindowScene` from the `UIApplication`](https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/Support/ManageSubscriptionsHelper.swift#L125), haven't had any issues with it so far

**Comment by aboedo** [comment] 2022-02-10 14:20
If you're using RevenueCat, our V4 SDK has a wrapper around StoreKit's method that already gets the window scene for you, you can access it through `Purchases.shared.showManageSubscriptions()`. [Docs here](https://revenuecat-docs.netlify.app/documentation/revenuecat/purchases/showmanagesubscriptions())

**Comment by haarj** [comment] 2022-02-10 15:50
Haven't moved to V4 yet. Is this basically the Obj-C version of that?

UIWindowScene *windowScene;
for (UIWindowScene *scene in [UIApplication
sharedApplication].connectedScenes) {
    if (scene.activationState == UISceneActivationStateForegroundActive) {
       windowScene = scene;
       break;
    }
}

I tried that and it's still freezing for me. So weird. Nothing in the
console logs. I'll wait until iOS 15.4 and see what happens.

Thanks for your help!

**Comment by haarj** [comment] 2022-02-11 11:49
Yea @aboedo I looked at the hierarchy and saw nothing overlaid on top of everything. :( Now this is just happening on a device and not simulator.

**Comment by aboedo** [comment] 2022-02-16 13:29
🤔 @haarj no relevant messages in the console, right? 

I wonder if it's just fighting the current hierarchy. Like, is the view you're presenting from itself presented as a modal? 

Do other features like [`presentCodeRedemptionSheet`](https://revenuecat-docs.netlify.app/documentation/revenuecat/purchases/presentcoderedemptionsheet()) work correctly when called from the same place?

**Comment by haarj** [comment] 2022-02-16 17:32
Hey @aboedo. No messages in the console, nothing in the view hierarchy that indicates anything on top of my presenting view. The view I'm presenting it from was pushed onto a navigation controller. "presentCodeRedemptionSheet" worked fine, however, I don't have offer codes setup so the page never loaded anything. Just a white screen. Only way to dismiss was to swipe down, which is different from the problem where I dismiss the manage subscription page by tapping on "Cancel" or the "X" in the top right hand corner.

**Comment by aboedo** [comment] 2022-02-16 19:30
🤔 okay... Could you try calling [`beginRefundRequest`](https://developer.apple.com/documentation/storekit/transaction/3803220-beginrefundrequest#) to see if the issue is the presentation itself or just limited to the manage subscriptions feature? 
`beginRefundRequest` was introduced at the same time as `showManageSubscriptions`, and it's supposed to behave similarly, so maybe it'll tell us a bit more?

**Comment by haarj** [comment] 2022-02-16 20:31
Same behavior as showManagedSubscriptions when clicking on the top right "x". With this stuff...
`DEBUG: ℹ️ PaymentQueue removedTransaction: com.eden.week 1000000970652950 (1000000617282765 (null)) (null) - 1
2022-02-16 15:29:47.877369-0500 Eden[10406:2072096] [tcp] tcp_output [C15.1.1:3] flags=[R.] seq=503375382, ack=3624932573, win=2047 state=CLOSED rcv_nxt=3624932573, snd_una=503375305
2022-02-16 15:29:48.113472-0500 Eden[10406:2072096] [tcp] tcp_input [C7.1.1:3] flags=[R] seq=1158682780, ack=0, win=0 state=CLOSED rcv_nxt=1158682780, snd_una=902501921
2022-02-16 15:29:48.122048-0500 Eden[10406:2072096] [tcp] tcp_input [C7.1.1:3] flags=[R] seq=1158682780, ack=0, win=0 state=CLOSED rcv_nxt=1158682780, snd_una=902501921
2022-02-16 15:29:48.179342-0500 Eden[10406:2072096] [tcp] tcp_output [C16.1.1:3] flags=[R.] seq=1733216528, ack=3245854576, win=2047 state=CLOSED rcv_nxt=3245854576, snd_una=1733216451
2022-02-16 15:29:52.556173-0500 Eden[10406:2072095] [tcp] tcp_output [C21.1.1:3] flags=[R.] seq=2826965870, ack=2634334283, win=2047 state=CLOSED rcv_nxt=2634334283, snd_una=2826965793
2022-02-16 15:29:53.505423-0500 Eden[10406:2072095] [tcp] tcp_output [C1.1.1:3] flags=[R.] seq=552739574, ack=1801553341, win=2047 state=CLOSED rcv_nxt=1801553341, snd_una=552739497
`

**Comment by haarj** [comment] 2022-02-16 20:41
Not sure if this helps but when the app freezes, my UI doesn't undim either. When the showManageSubscriptions page opens my interface dims and then when clicking the "x" it never undims. My app only undims and becomes functional again when I swipe to dismiss the page. I have a feeling this is an Apple issue. Why would swipe to dismiss work and not the "x"?

**Comment by aboedo** [comment] 2022-02-17 13:50
yeah, I wouldn't be surprised if it was an apple bug... Have you tried on 15.4? Maybe they fixed it. If not, I think this is worth filing a radar for. 
I'd be happy to file it, do you have a sample project or something that I can use to reproduce, since I haven't been able to do it on my end yet?

**Comment by haarj** [comment] 2022-02-17 16:08
Let's cross the bridge when we really need to when many clients are experiencing this and not just me. I'm just going to wait until 15.4 RC comes out. Not the worst thing in the world for me at the moment. So just going to sit on it for now.

**Comment by aboedo** [comment] 2022-06-27 12:57
@haarj did you get a chance to confirm whether this is still an issue with 15.4 final?

**Comment by haarj** [comment] 2022-06-28 10:12
@aboedo looks to be working on my current device running iOS 15.5 either by swiping down the subscription sheet or pressing the X. So I think we are good here now.

**Comment by aboedo** [comment] 2022-06-28 19:35
That's great to hear!! I'll close this out for now but feel free to reopen if you run into it again. Thanks for reporting back! 💪

**Closed by aboedo** 2022-06-28 19:35 UTC
Labels: bug, triaged
