### ISSUE TITLE
v3.6.0-beta - nonRecurringSubscriptions not accessible in Swift project

### ISSUE THREAD

**Issue by dmonagle** [RevenueCat/purchases-ios#314] opened 2020-08-13 08:00 UTC
I've noticed the addition of nonRecurringSubscriptions on Purchases.PurchaserInfo in v3.6.

I attempted to access this only to be told that **Value of type 'Purchases.PurchaserInfo' has no member 'nonSubscriptionTransactions'**

I'm spent some time digging through the code, but unfortunately it's been years since I worked with ObjectiveC and I've never had to work with them both in the same project. My initial suspicion is that it was because it is defined as

```objc
NSArray<RCTransaction *> *nonSubscriptionTransactions;
```

And that RCTransaction which is a Swift class **Transaction**, is internal and part of the PurchasesSwift target. At this point I feel I'm just guessing as to what the problem might be, but it sure would be handy to have access to the nonSubscriptionTransactions property from Swift.

Thanks guys.

**Comment by aboedo** [comment] 2020-08-13 13:55
you're correct, I spotted this yesterday and figured it might be an issue. we'll make the class public.

**Comment by dmonagle** [comment] 2020-08-14 02:37
This is related, for the 3.6.0 release and I'm happy to open another issue if needed. While the library builds and runs fine within a project, test targets for a project are failing to build with the following errors:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/569687/90207875-ba12ac00-de2a-11ea-85f6-b639551dd04d.png">

This was not an issue with 3.5.2 so I assume this is also a byproduct of the hiding of internal Swift interfaces.

**Comment by aboedo** [comment] 2020-08-14 14:06
Thanks for reporting! I'll take a look at that as well. 
Question: when you say "tests targets for a project" do you mean test targets on your own project or the ones from `purchases-ios`?

**Comment by aboedo** [comment] 2020-08-14 15:03
@dmonagle also, how are you importing `purchases-ios`? As in, are you using cocoapods, carthage, SPM, direct download of the binary or compiling directly from source?

**Comment by dmonagle** [comment] 2020-08-14 23:31
Oh sorry. Yes the test targets on my project. It’s actually more than just building for testing that’s an issue. Archive fails for the same reason. I’m using Swift Package Manager exclusively in the project. 

Making those classes public fixes the issue, but obviously the goal was to keep the internals internal. Unfortunately I have no experience with creating mixed packages so I can only feed back my experiences.

**Comment by aboedo** [comment] 2020-08-15 10:48
thanks for the info, that'll help reproduce the issues. I'll make sure to get it working. our package on SPM does have a bit of a different structure compared to the rest since SPM doesn't support mixed-language targets, which made us make a split between objc and swift. But this should be fixable.

**Comment by aboedo** [comment] 2020-08-31 19:09
3.6.0-beta-2 should address this @dmonagle. Thanks for your patience with this. It took longer than expected to get a fix out because this led us to restructure our code quite a bit, but I tested it on SPM as well as Cocoapods and Carthage and it should be working correctly and archiving with no issues. 

Let me know if you run into anything else, and thanks again for reporting!

**Comment by aboedo** [comment] 2020-09-14 18:12
@dmonagle 3.6.0 final has been released! closing this issue now.

**Closed by aboedo** 2020-09-14 18:12 UTC
Labels: bug, next_release
