### ISSUE TITLE
Public init() for Package and Offerings

### ISSUE THREAD

**Issue by janandre** [RevenueCat/purchases-ios#1563] opened 2022-05-11 06:45 UTC
Dear RevenueCat developers,

We just migrated to 4.0 and really like the swift experience. Well done!

Currently, I am building some Paywalls we want to A/B test.
SwiftUI & Previews are a great tool, therefore!

However, we initialize our view model with our different packages.
To be able to use Previews, a public init would be really handy to create the mock data.

Is there a reason why they are fileprivate at the moment?
Of course, I could create my own wrapper object, but that does not feel native to me.

Best regards,
Jan André

**Comment by joshdholtz** [comment] 2022-05-11 13:01
@janandre Thanks for the kind words! Glad you found the 4.0 experience enjoyable 😊 

One of the things we have planned and have received other feedback about it being able to mock our models a little bit easier. We have not received feedback about being able to mock or initialize them for Previews (which totally makes since) but we have received feedback about being able to mock our models better in tests.

I'll group this feedback into that other one so they can get thought about together! 😁 

cc: @NachoSoto

**Comment by Kaspik** [comment] 2022-05-13 08:50
Another reason for mocks would be developers that also internally ship builds through Enterprise accounts - those don§t have AppStore Connect thus can't get Packages and Offerings. We can detect this in the code, and in RevenueCat 3.x we mock empty packages. But with 4.x it's not possible anymore.

@joshdholtz It would be great if public inits would be available again in 4.x (even empty init is fine for now) sooner rather than later.

**Comment by NachoSoto** [comment] 2022-05-13 15:04
There is some [internal discussion](https://revenuecats.atlassian.net/browse/CF-631) about how to best address this.

I actually started the process of opening a PR over a year ago to expose initializers to the then Obj-C types (back in version 3.x), and after some hours going down this rabbit hole, I realized that there is only so much RevenueCat can do. Most (if not all) StoreKit types don’t have constructors and or aren’t mutable. Even SK2’s `struct` types suffer from the same problem.

Considering this, it is my opinion that the best approach from an app’s perspective is to create your own models that can be backed by RC/SK types or fake data. Then inject these types to SwiftUI previews, tests, etc.

This is how I do it in my app. Notice how I have the properties that I need to use, and 2 constructors: one from `Purchases.Package`, and the other one with fake data that I can instantiate manually (only on debug).

![image](https://user-images.githubusercontent.com/685609/168312146-2539bcb6-0bd1-40ec-8fc8-f4481ed9d4fd.png)

**Comment by haIIux** [comment] 2022-07-02 02:41
I'm unsure if my issue I'm having is caused by the missing `init()` for Package and Offerings, if it is not, please let me know and I will gladly create a new issue.

When attempting to build out a paywall view, the below code crashes my Xcode previews. 

```
if revenueCat.isProUser {
   SubscribedBanner()
} else if let currentOffering = currentOffering {
   ForEach(currentOffering.availablePackages) { package in
                        
   }
}
```

As soon as I write the above bit (mainly the `else if let` portion, I get the following error...

```
Incident Identifier: AA212F7C-4749-4531-9B80-39E0A4482843
CrashReporter Key:   BEF69C9D-CF8D-5B49-999B-99E7E49C1E3B
Hardware Model:      MacBookAir10,1
Process:             HeatBuddy [68839]
Path:                /Users/USER/Library/Developer/Xcode/UserData/Previews/Simulator Devices/895269E3-0EF1-42FD-A238-5E00F4EC64CA/data/Containers/Bundle/Application/D2E59E45-01E4-4EBE-AD41-A61017BA2BDB/HeatBuddy.app/HeatBuddy
Identifier:          com.TenEightStudios.HeatBuddy
Version:             1.0.4 (6)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [62724]
Coalition:           com.apple.CoreSimulator.SimDevice.895269E3-0EF1-42FD-A238-5E00F4EC64CA [45648]
Responsible Process: SimulatorTrampoline [1661]

Date/Time:           2022-07-01 22:34:28.3752 -0400
Launch Time:         2022-07-01 22:34:27.7529 -0400
OS Version:          macOS 12.4 (21F79)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x000000018f70f568
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 5 Trace/BPT trap: 5
Terminating Process: exc handler [68839]

Triggered by Thread:  0

Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage

```

**Comment by NachoSoto** [comment] 2022-07-04 01:27
This looks like just a Swift compilation error, unrelated to this issue. 
```swift
ForEach(currentOffering.availablePackages) { package in // if you use any other array here, you'd get the same issue
  // Does it crash too if you return any view here? Like:
  EmptyView()                        
}
```

**Comment by taquitos** [comment] 2022-07-29 19:14
Heya, it's been a little while, it looks like this issue has been solved for you, so I'm going to close it out. Feel free to create a new issue if the problem still persists!

**Comment by Kaspik** [comment] 2022-07-29 19:38
Where did the internal discussion go, or what's the result of https://github.com/RevenueCat/purchases-ios/issues/1563#issuecomment-1126156049 ?

**Comment by taquitos** [comment] 2022-07-29 21:13
We think there are a few options:
1. Document the approach @NachoSoto mentioned, the motivations, and offering sample code like this.
1. Provide a separate repo that has types like this, and maybe some SwiftUI helpers that we’ve talked about in the past.
1. Expose the protocols like StoreProductType so users can implement that with mocks. This may sound trivial, but it’s not necessarily an acceptable solution for reasons explained in the previous comment- You keep going down the rabbit hole, and eventually you can’t create a mock discount because you can’t instantiate a Product.SubscriptionOffer.

We have a jira opened [CSDK-40] in our system to track this, too.

**Comment by NachoSoto** [comment] 2023-06-23 20:42
I'm reopening this issue because we're currently considering an approach to finally allow creating test products and offerings.

**Closed** 2023-06-29 21:06 UTC
Labels: enhancement, sharpen the saw, triaged
