### ISSUE TITLE
Purchase already in progress for this product

### ISSUE THREAD

**Issue by RamblinWreck77** [RevenueCat/purchases-ios#291] opened 2020-07-23 20:24 UTC
Hello! Starting with SDK 3.5.0 (we haven't shipped 3.5.1 yet) we've been seeing some odd errors in production. It appears that sometimes when a user canceled a purchase then tries to purchase again RevCat can throw an already-in-progress error

1. Environment
    1. Platform: iOS
    2. SDK version: 3.5.0
    3. OS version: 12-13
    4. XCode/Android Studio version: 11.6
    5. How widespread is the issue. Percentage of devices affected. 0.5-1%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce: Unable to reproduce at this time, still attempting

**Additional context**
Here's an excerpt from our prod logs for an effected user, they pretty much all look like this:

User :

```
Jul 22 17:59:50  🎁 Saw Sell page flow: setupSensor, sku: ***   <Saw our sell page
Jul 22 17:59:59  💰 Initiating Purchase: ***                    <User hit purchase, Purchases.shared.purchasePackage(package) Called
Jul 22 18:00:01  💰 Purchase State: .purchasing                 <Our own SKPaymentTransactionObserver sees the state change
Jul 22 18:00:03  🚀 Application - WillResignActive              <User sees native pay sheet
Jul 22 18:01:31  🚀 Application - DidBecomeActive               <User exists native pay sheet
Jul 22 18:01:31  💰 User Canceled Purchase                      <Purchases.shared.purchasePackage returned userCancelled == true
Jul 22 18:01:31  🎁 Premium Popup: User Cancel
Jul 22 18:01:32  ⛓ Got Branch params: [AnyHashable("+is_first_session"): 0, AnyHashable("+clicked_branch_link"): 0]
Jul 22 18:01:33  💰 Initiating Purchase: ***
Jul 22 18:01:33  💰 Purchase State: .purchasing
Jul 22 18:01:34  🚀 Application - WillResignActive
Jul 22 18:20:21  🚀 Application - DidBecomeActive‰‰
...
Jul 22 18:20:21  ⛓ Got Branch params: [AnyHashable("+clicked_branch_link"): 0, AnyHashable("+is_first_session"): 0]
Jul 22 18:20:40  🎁 Saw Sell page flow: scanFooter(index: 1), sku: ***
Jul 22 18:20:46  💰 Initiating Purchase: ***
Jul 22 18:20:46  💰 🔥🔥🔥 Purchase Error: {Unknown Error Type}: Type: NSError, Description: Purchase already in progress for this product.
Jul 22 18:20:46  💰 🔥 Rcat: operationAlreadyInProgressError
Jul 22 18:20:46  🎁 Premium Popup: 🔥 Other Error!
Jul 22 18:20:46  🔥🔥🔥 PRODUCTION NON-FATAL ERROR: Other error in PremiumSellVC
Jul 22 18:20:46  🔥🔥🔥 PURCHASE: DEFAULT ERROR! Type: {Unknown Error Type}: Type: NSError, Description: Purchase already in progress for this product., typeString: operationAlreadyInProgressError 
```

In every case a user starts, then cancels (sometimes up to 3 times) and then becomes unable to purchase going forward until force quitting/relaunching the app. We've had RevCat for a while and haven't seen this problem until our most recent version with the 3.5.0 SDK. Is it possible canceled transactions aren't getting cleared intermittently?

**Comment by rkotzy** [comment] 2020-07-27 16:59
Do all of the cancellations return with `userCancelled == true`? Or does the last one hang in the `💰 Purchase State: .purchasing` state? 

That error message is expected if there is already a pending purchase completion block with the same product ID that hasn't finished yet.

**Comment by RamblinWreck77** [comment] 2020-07-27 17:27
Nope. A !userCancelled guard is the first code in the callback

<img width="736" alt="Screen Shot 2020-07-27 at 1 24 52 PM" src="https://user-images.githubusercontent.com/22692130/88572216-cadeb780-d00c-11ea-818f-2d9bf4097697.png">


so it's impossible to get to the log that checks for an error

```
💰 🔥🔥🔥 Purchase Error:
```

Without it being false

**Comment by RamblinWreck77** [comment] 2020-07-27 17:28
Also:

```
🎁 Saw Sell page flow:
```

Fires in the viewWillAppear of the sell page

**Comment by aboedo** [comment] 2020-08-04 14:36
I have a suspicion that this might be related to https://github.com/RevenueCat/purchases-ios/issues/292, where the new error cases are being used. Even though the new error cases where added very recently (with Xcode 12 beta seed 3), the docs say that [this one](https://developer.apple.com/documentation/storekit/skerrorcode/skerroroverlaycancelled?changes=latest_min_4_5_____8) could show up with iOS 12.2+

**Comment by RamblinWreck77** [comment] 2020-08-04 17:52
@aboedo in this case the "Default error" warning in the logs is from the @unknown default handler warning that "operationAlreadyInProgressError" was not an expected case.

**Comment by aboedo** [comment] 2020-08-04 18:32
@RamblinWreck77 good catch - in that case it can only have been triggered here: https://github.com/RevenueCat/purchases-ios/blob/develop/Purchases/Public/RCPurchases.m#L620. 
It looks like the completion block for the first purchase wasn't removed, even though it was called. We'll dig in further

**Comment by RamblinWreck77** [comment] 2020-08-10 17:57
@aboedo Any update on this issue? At this point it is accumulating to a small (but not exactly insignificant) number of sales.

**Comment by aboedo** [comment] 2020-08-10 22:45
@RamblinWreck77 this is super tricky to reproduce since it seems to stem from a race condition when accessing the `purchaseCompleteCallbacks`.
I found one place where multi-threading could be improved. I'm going to make a PR for it. I'm not sure it will solve your case, since it's really hard to reproduce.

**Comment by aboedo** [comment] 2020-08-11 14:22
@RamblinWreck77 here's the PR I mentioned: https://github.com/RevenueCat/purchases-ios/pull/313

And here is the bug it fixes: https://github.com/RevenueCat/purchases-ios/pull/313/files#r468619549. Is there any chance you have something like that in your code? where a flow that starts on the completion block might initiate a new purchase?

**Comment by aboedo** [comment] 2020-08-11 14:22
for example, a retry mechanism

**Comment by RamblinWreck77** [comment] 2020-08-11 14:49
Yes, we have a network-failure retry mechanism. That could be the culprit/triggering the race condition!

**Comment by aboedo** [comment] 2020-08-11 15:51
@RamblinWreck77 awesome!! Glad to have found an explanation. We'll get the fixed shipped soon so retries work correctly. Thanks for reporting and for following up!! Cool emoji logs by the way 🔥 super easy to spot errors

**Comment by aboedo** [comment] 2020-08-31 19:11
@RamblinWreck77 heads up that we have a new beta build, 3.6.0-beta-2, which includes this fix along with a few others. Feel free to check it out. It should go into stable relatively soon assuming no big surprises.

**Comment by aboedo** [comment] 2020-09-14 18:13
@RamblinWreck77  3.6.0 final has been released! closing this issue now.

**Closed by aboedo** 2020-09-14 18:13 UTC
Labels: bug, next_release

**Comment by RamblinWreck77** [comment] 2020-09-14 18:57
Great! We'll QA + ship this soon, and keep you posted on any potential regressions.

**Comment by aboedo** [comment] 2020-09-14 19:01
awesome thank you!

**Comment by tayyabjamil** [comment] 2023-01-26 18:43
The operation is already in progress for this product.
Is there any way to  manually cancel pending or in progress transactions..?

**Comment by aboedo** [comment] 2023-01-26 18:47
if you're using storeKit configuration files, you should be able to manage transactions directly from Xcode. If you're not using StoreKit Configuration files, you can go into settings -> App Store -> Sandbox User -> Manage Subscriptions and then manage existing transactions

**Comment by localboss-git** [comment] 2023-02-28 17:45
I have a couple of users who got this in production "Purchase already in progress for this product"
is there something I'm doing wrong?

**Comment by aboedo** [comment] 2023-03-03 20:45
@localboss-git 🤔  one way to get it in production is if you allow for the purchase button to be tapped while a purchase is still in progress (i.e.: if you don't block the button while waiting for the callback from `purchase`)

**Comment by localboss-git** [comment] 2023-03-03 22:25
BTW I solved this by changing the configuration in Localboss, I had the setting of Restore behavior to `Block restores`.

**Comment by Accessibilly** [comment] 2024-04-24 14:17
> @localboss-git 🤔 one way to get it in production is if you allow for the purchase button to be tapped while a purchase is still in progress (i.e.: if you don't block the button while waiting for the callback from `purchase`)

This same issue occurred for me, and was the cause of an App Store rejection for a recent build of my app. Thankfully I found this thread (!). The error was straightforward to reproduce using a sandbox account: intentionally double tap the subscribe / purchase button before Apple's confirmation dialog appears, and an error dialog will pop up indicating a purchase is already in progress.

The code fix was as simple as @aboedo mentioned:

1. In the handler for purchaseButton's activation, set purchaseButton.isEnabled = false
2. In the closure for Purchases.shared.purchase(package:), after the logic to handle the package purchase (or error), set self.purchaseButton.isEnabled = true
