### ISSUE TITLE
Non-renewing subscription rejection 

### ISSUE THREAD

**Issue by ozgurshn** [RevenueCat/purchases-ios#234] opened 2020-05-06 10:07 UTC
Hello, I'm using the same PayWall in this repo as a payment screen. I have a non-renewing product. In my previous version, PayWall was directly presented to the user after launching the app. Now in this rejected version, I only moved the Paywall from the app start to the behind of 'download' button. Now the user transforms the image and performs the basic function of the app and then PayWall shown if the user wants to download the image. 
What do you guys advise me to handle this rejection?

Guideline 3.1.1 - Business - Payments - In-App Purchase

We found that your app includes a feature to restore previously purchased in-app purchase products by entering the user's Apple ID and password. However, non-renewable subscriptions in-app purchases cannot be restored in this manner.

To resolve this issue, please revise your binary to implement your own restore mechanism, if you would like users to be able to restore non-renewable subscriptions in-app purchase products.

More information on in-app purchase product types is available in App Store Connect Help.

Guideline 3.1.2 - Business - Payments - Subscriptions

Your app offers a content subscription but does not have a mechanism in place to support the requirement that the subscription content be available to the user on all of their iOS devices.

Next Steps

To resolve this issue, please modify your app to include an optional user registration feature to deliver subscription content to all of the user's iOS devices. Such user registration must be made optional, not required. We also recommend indicating that registering is required to access the subscription content from their other iOS devices - and providing a way to register later, if users wish to have access to this content at a future time.

**Comment by aboedo** [comment] 2020-05-06 13:36
Hi! This looks like a configuration issue. Please take a look at the FAQ and file a ticket if necessary [in our support site](https://support.revenuecat.com/), since they'll be able to provide better assistance. 
From the message, though, it looks like the issue isn't with the paywall location, but rather with the products. 
It's common for one app version to make it through review and another version getting rejected, you just might be getting a different reviewer. 

My interpretation of the issue is that you've set up a non-renewing subscription, and you have a purchase button that calls `restoreCompletedTransactions`, which doesn't actually restore non-renewing subscriptions. To restore those, you need to use a refreshReceiptRequest instead (this is what RevenueCat's [restore feature](https://sdk.revenuecat.com/ios/Classes/RCPurchases.html#/c:objc(cs)RCPurchases(im)restoreTransactionsWithCompletionBlock:) does). 

The reviewer's suggestion here is to create an accounts system on your app, so users can log in and get their purchased content that way. 

My suggestion would be to reconsider whether you really need non-renewing subscriptions, since they're not widely adopted, are trickier to implement and don't market very well, but that's entirely up to you and your use case. If you don't need them, going with auto-renewable subscriptions will be much less of a headache. 

I'm closing this issue for now since it's related to App Store Connect configuration, but feel free to [contact RevenueCat support](https://support.revenuecat.com/) if you need further assistance figuring this out.

**Closed by aboedo** 2020-05-06 13:36 UTC

**Comment by ozgurshn** [comment] 2020-05-06 13:46
Hi @aboedo, thanks for the clarification. Apple didn't let me use auto-renewing subscriptions in my previous version so I switched to non-renewing. I will search for the ways back to auto-renew IAP. I will check the links you mentioned, thanks.
